### ISSUE TITLE
MineStackへのアイテム登録や履歴表示に関するバグ

### ISSUE THREAD

**Issue by karayuumac** [GiganticMinecraft/SeichiAssist#10]
内部処理的な問題で同じアイテムで異なるLoreや名前のアイテムをMineStackに入れた際、正常な動作をしない。
例えば、現時点ではガチャアイテムである「ホームランバット」を取り出したとしても履歴に表示されるのは「ブレイズロッド」となっている。

**Comment by kory33** [comment]
ガチャ品がそもそも履歴に表示されないように変更された上に多分ロジックも直っているのでcloseします
