### ISSUE TITLE
アサルトの破壊対象ブロックにベッドなどを追加する

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1027]
第11回アイデア会議にて承認された
https://redmine.seichi.click/issues/9315

* [x] ベッド (#913)
* [x] TNT (#913)
* [x] 醸造台 (#913)
* [x] ハーフブロック全種類（上付き、下付き）
  * [x] 木のハーフブロック各種 (#913)
  * [x] 石のハーフブロック各種

**Comment by KisaragiEffective** [comment]
All tasks have been done.
