### ISSUE TITLE
gachaコマンドが反応せず投票特典が反映されていない

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#1052]
/gacha vote `playername` が機能していない模様。
当該コマンドを実行するとコンソール上には何も出力されない。`Unknown command. Type "/help" for help.`すらもでない。

**Comment by Lucky3028** [comment]
4f1079f2af1bfb2e069673e261007ccdc73fe65a により、「/vote record」コマンドになっているようです。@unchama

**Comment by unchama** [comment]
理解。整地鯖春のvoteコマンドとかぶっていて機能していなかったのでSimpleVoteListener内で以下の記述をすることにより対応します。
```
commands:
  - 'giganticlistener:vote %name% 1'
  - 'seichiassist:vote record %name%'
```

**Comment by KisaragiEffective** [comment]
そのようなプレフィクスをつけることで解消可能です。解消されたようなので、一応クローズしておきます。
