### ISSUE TITLE
/presentコマンドがすべて動作しない

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1054]
/present [player name]とだけ表示される

**Comment by Lucky3028** [comment]
というか、全部のサブコマンドを実行しても、同じメッセしか出ないですね

**Comment by Lucky3028** [comment]
あ、もしかして、pexの権限付与してないから？

**Comment by KisaragiEffective** [comment]
どうも`/present`全体に`seichiassist.present`がかかっているようで (see: #1057)、お手数ですが左記ノードの付与をお試しいただけませんか？

**Comment by Lucky3028** [comment]
了解です

**Comment by Lucky3028** [comment]
症状変わらず😔

**Comment by KisaragiEffective** [comment]
あるいは、考えられる可能性としては`seichiassist.present.*`を付与すると動作するやもしれません

**Comment by Lucky3028** [comment]
ありがとうございます、変わらないですね…

**Comment by Lucky3028** [comment]
どうして...

**Comment by kory33** [comment]
これなんですけど、そもそもpresentSystemを宣言だけしてBukkitに繋げてなくないですか…？

**Comment by KisaragiEffective** [comment]
あれ…？

**Comment by KisaragiEffective** [comment]
fixed in e43641b

**Comment by KisaragiEffective** [comment]
seems not fixed yet

**Comment by kory33** [comment]
認識すらしないのは e43641b で直りました
個別のサブコマンドに問題があった場合は別のissueを起票してください
