### ISSUE TITLE
遠距離整地スキルで矢が飛ばない

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1063]
コンソールのログ

> [Sat, 3. Jul 2021 15:10:43 JST INFO] ArrowEffectを非同期で実行する最中にエラーが発生しました。
[Sat, 3. Jul 2021 15:10:43 JST WARN] java.lang.IllegalStateException: Asynchronous entity add!
[Sat, 3. Jul 2021 15:10:43 JST WARN] at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1017)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1115)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.addEntity(CraftWorld.java:1221)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawn(CraftWorld.java:1228)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawn(CraftWorld.java:863)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at com.github.unchama.util.effect.BukkitResources$.$anonfun$vanishingEntityResource$1(BukkitResources.scala:24)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at make @ com.github.unchama.seichiassist.subsystems.expbottlestack.bukkit.Resources$.bottleResourceSpawningAt(Resources.scala:17)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at make @ com.github.unchama.seichiassist.subsystems.expbottlestack.bukkit.Resources$.bottleResourceSpawningAt(Resources.scala:17)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at allocated @ com.github.unchama.generic.effect.ResourceScope$MultiDictResourceScope.useTracked(ResourceScope.scala:148)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at map @ com.github.unchama.generic.effect.ResourceScope$MultiDictResourceScope.useTracked(ResourceScope.scala:148)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at flatMap @ com.github.unchama.generic.effect.ResourceScope$MultiDictResourceScope.useTracked(ResourceScope.scala:148)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at map @ com.github.unchama.seichiassist.seichiskill.effect.arrow.ArrowEffects$.$anonfun$arrowEffect$9(ArrowEffects.scala:119)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at map @ com.github.unchama.minecraft.bukkit.actions.OnBukkitServerThread.$anonfun$runAction$9(OnBukkitServerThread.scala:50)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at flatMap @ com.github.unchama.minecraft.bukkit.actions.OnBukkitServerThread.$anonfun$runAction$5(OnBukkitServerThread.scala:29)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at flatMap @ com.github.unchama.minecraft.bukkit.actions.OnBukkitServerThread.runAction(OnBukkitServerThread.scala:25)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at map @ com.github.unchama.seichiassist.seichiskill.effect.arrow.ArrowEffects$.$anonfun$arrowEffect$3(ArrowEffects.scala:97)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at flatMap @ com.github.unchama.seichiassist.seichiskill.effect.arrow.ArrowEffects$.$anonfun$arrowEffect$3(ArrowEffects.scala:97)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at unsafeRunSync @ com.github.unchama.datarepository.bukkit.player.BukkitRepositoryControls$Initializers$$anon$2.onPlayerJoin(BukkitRepositoryControls.scala:107)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at unsafeRunSync @ com.github.unchama.datarepository.bukkit.player.BukkitRepositoryControls$Initializers$$anon$2.onPlayerJoin(BukkitRepositoryControls.scala:107)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at apply @ com.github.unchama.generic.effect.unsafe.EffectEnvironment.runAsyncTargetedEffect(EffectEnvironment.scala:34)
[Sat, 3. Jul 2021 15:10:43 JST WARN] at apply @ com.github.unchama.generic.effect.unsafe.EffectEnvironment.runAsyncTargetedEffect(EffectEnvironment.scala:34)

**Comment by KisaragiEffective** [comment]
メモ: `OnMinecraftThread`
