### ISSUE TITLE
[SQL]statementやresultsetの閉じ忘れ

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#107]
statementやresultsetの閉じ忘れを所々忘れているので閉じるようにする。
閉じ忘れててもGC時に閉じるらしいけど、その分GCが重くなるらしい……とgoogle先生が仰っておりました。

**Comment by kory33** [comment]
Scalikejdbcに対処を任せるべき

**Comment by KisaragiEffective** [comment]
多分解消したので閉じる
