### ISSUE TITLE
レベルアップすると送信される 『レベルアップ記念のアイテムを配布しました。』が大量に送信される

### ISSUE THREAD

**Issue by merunno** [GiganticMinecraft/SeichiAssist#1084]
![image](https://user-images.githubusercontent.com/82575685/125394601-e3460e80-e3e4-11eb-8c3a-0655359f4fce.png)

- #1049 に含まれたissueでしたら申し訳ないです。
- 既出のバグでしたらすみません。Closeで構いません。

**Comment by Lucky3028** [comment]
#1048 ですね、すみません

**Comment by merunno** [comment]
Oh... ありがとうございます。

**Comment by Lucky3028** [comment]
こちらこそご報告ありがとうございます！
