### ISSUE TITLE
リリースがだるい

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#1085]
- #1041 のように変更履歴を手で列挙するのは滅茶苦茶めんどくさい
 - GitHub Actionsで以下をしたい
   - `workflow_dispatch` でmajor/minor/patchバージョンのうちbumpしたいものを選べる
   - `build.sbt/version` をbump
   - `master` をマージし、`develop` -> `master` へのPRを作成する
     - PR内に変更を列挙する(PRと直コミットを分けていいかも)

**Comment by xenolay** [comment]
puny~

**Comment by kory33** [comment]
とりあえずリリース自体はだるくなくなった
