### ISSUE TITLE
[SQL]接続復旧処理がダブる

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#109]
プレイヤーが2人以上且つDB接続が切れてしまった状態でPlayerDataBackupTaskRunnableが走ると、ensureConnection()が非同期でプレイヤー人数分実行されてしまっている。
試しにDBをモニタリングしたところ、コネクション数がプレイヤー数分張られてしまっている模様。気持ち悪いのでそのうち直す。

synchronized拡張子とやらを使えばいけるらしいが、同一インスタンス内からの呼び出しのみ正常に機能するとか。なんもわからん
https://www.google.co.jp/search?q=synchronized+java+%E6%84%8F%E5%91%B3&ie=UTF-8&oe=UTF-8&hl=ja-jp

**Comment by kory33** [comment]
Scalikejdbcへの置き換えを行えば直ります

**Comment by KisaragiEffective** [comment]
多分解消したので閉じる
