### ISSUE TITLE
整地レベルアップのメッセージの括弧がまだ消せていなかった

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1091]

**Comment by KisaragiEffective** [comment]
どこです…？

**Comment by Lucky3028** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/e7c39d3fb5df5a55651bdfc65386496d0e788ec3/src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala#L38
これです
