### ISSUE TITLE
MineStackのアイテム登録の簡略化

### ISSUE THREAD

**Issue by karayuumac** [GiganticMinecraft/SeichiAssist#11]
現時点ではソースコードに全アイテムを記載してMineStackのアイテムを管理している。
この方法では、ソースコード編集作業を行わなければならず、開発者が必要となる。

そのため、現在のMineStackのガチャアイテム登録のシステムのような、手に持ったアイテムをコマンドを打つことによってMineStackに登録できるような機能を追加したい。

**Comment by rito528** [comment]
MineStackのアイテムは、現在ハードコーディングされているのでクローズ
