### ISSUE TITLE
破壊音が複数回なっている可能性

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#111]

**Comment by Megumiso** [comment]
スキル使用時、スキルによって破壊されるブロックがなかった場合に発動することが判明しました。
例: デュアル・ブレイクを上向きにした状態で、ブロックを破壊したとき、上にブロックがないときなど

**Comment by kory33** [comment]
スキル周りかなり書き換わったので恐らくfixされています
