### ISSUE TITLE
スキルで破壊したときに出るエフェクトが違う

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#112]
例えば、一括破壊で白樺の原木を壊したときに、オークの原木の破壊エフェクトが出る。

**Comment by KisaragiEffective** [comment]
本来の破壊で本来のエフェクトが出る ---> スキルで各ブロック (**しかしメタデータはゼロ**)のエフェクトが出るという流れ・・・？

**Comment by yuuki1293** [comment]
現在修正されています

**Comment by rito528** [comment]
情報ありがとうございます！
