### ISSUE TITLE
Scalafixほしい

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#1153]

**Comment by kory33** [comment]
[こないだ作ったプロジェクト](https://github.com/kory33/itemstack-count-infrastructure/tree/22721250c3e8bb2688538e3933a5f5f998406c2c)でCIでのlint/formatまでやってみましたけどかなり開発体験良かった　Scala3向けだけど設定の大半は参考にできそう

**Comment by KisaragiEffective** [comment]
昨日は冗長なContext boundsを検知したいなと思っていた。
下記コードでは`[A[_]] =>> ConcurrentEffect[A] <: Monad[A]` なので`Monad`制約をContext boundに書くのは冗長。

```scala
def foo[F[_] : ConcurrentEffect : Monad]: F[Unit] = ??? // ...
```

**Comment by KisaragiEffective** [comment]
* 冗長なContext boundsの検知
* early-referenceの検知 (これを踏むと訳のわからないところでNPEが出る)
* case classが生成したtoStringの暗黙の呼び出しの検知 (例: `sad: SeichiAmountData` であるときに `s"整地量: ${sad}"` とするなど)

**Comment by kory33** [comment]
挙げられてた問題全部別issueに切った
