### ISSUE TITLE
アサルト解放通知BOTにも、旧社会の歯車BOTと同じように画像をつける

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1160]
https://redmine.seichi.click/issues/9845
ダイヤモンドのチェスト・プレート？

**Comment by KisaragiEffective** [comment]
webhookの設定をいじればセットできるのでは？out-of-scopeっぽそう

**Comment by KisaragiEffective** [comment]
![image](https://user-images.githubusercontent.com/48310258/132966581-0f47de9a-7e17-451c-b9f5-44b446ccfa89.jpeg)

**Comment by Lucky3028** [comment]
ありがとうございます！それでいいんですね、やります
