### ISSUE TITLE
接続時間オーバーフローしてる問題

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#1168]
from #1155

> で、なんと9500万秒くらい放置している人が存在していて、これが1億500万秒に到達するとその人の記憶が壊れるので、永続化層もちゃんと修正しないとじきに死にます　こちらは別issueで対応します
(edited by @KisaragiEffective - s/ティック/秒/g)

**Comment by kory33** [comment]
DB側での修正と、playtickをread/writeする箇所すべて、及びそれらを格納するデータクラスの修正が必要です

**Comment by KisaragiEffective** [comment]
もうオーバーフローしてる。
