### ISSUE TITLE
デバッグ環境のイメージをghcr.ioに移行する

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#1178]
[これ](https://github.com/GiganticMinecraft/SeichiAssist/blob/4e72064317e798f1ee98b20cd3f27bdf05a00858/docker-compose.yml#L115)とかが何故か古いコンテナレジストリを使っており `docker login` しないと使えないため、環境構築で詰まる人が続出しているらしい

**Comment by KisaragiEffective** [comment]
https://docs.github.com/ja/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry
