### ISSUE TITLE
棒メニューの建築量表記内容をわかりやすくする

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1195]
建築Lv、総建築量、次のレベルまでの3つが表記されていますが、「次のレベルまで」の部分が、「次のレベルになる総建築量」が記載されている。
「次のレベルまで」と表記するのであれば、整地量の次のレベルまでのように、「あとどれくらい建築をすると」というカウントダウンする方式に変更する。

第15回アイデア会議にて承認された。
https://redmine.seichi.click/issues/10110

**Comment by KisaragiEffective** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/71ecc0ded963f7c61658151ca44e14070055955b/src/main/scala/com/github/unchama/seichiassist/menus/BuildMainMenu.scala#L47
