### ISSUE TITLE
次のスターレベルまでの整地量の表記にカンマをつける

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1223]
第16回アイデア会議にて承認された。
https://redmine.seichi.click/issues/10241

**Comment by Lucky3028** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/26b7e89439c0f06cb34f40933b051c57175a7e49/src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/FirstPage.scala#L466-L469

**Comment by rito528** [comment]
すでに実装されていませんか...?
勘違いだったらごめんなさいm(_ _)m

実際の表示
https://gyazo.com/e7b7a1584c653b91aad13af92358d0d4

**Comment by KisaragiEffective** [comment]
ありがとうございます。クローズ
