### ISSUE TITLE
お初さんの画面に『このサーバーで遊ぶにはルールを読む必要があります。公式サイトを確認してください』のような文章をタイトル表示する

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1229]
https://redmine.seichi.click/issues/10227
第16回アイデア会議にて承認された

**Comment by merunno** [comment]
アイデア提案 `#10227` 拝見しました。

『このサーバーで遊ぶにはルールを読む必要があります。公式サイトを確認してください』

これくらいの長さをタイトルで流そうとするとお初さんのGUIサイズによっては見切れてしまって、本来期待される効果が発揮されない可能性があります。文章を変えるか、別の方法を見つけ出す必要があるかもしれません。

![image](https://user-images.githubusercontent.com/82575685/147904843-816c3db5-4b94-4e75-b768-02f5bf1b622e.png)

**Comment by Lucky3028** [comment]
ありがとうございます。そうすると、

タイトル
ルールは確認されましたか？
サブタイトル
公式サイトで確認できます

くらいでしょうか。

**Comment by merunno** [comment]
見切れずに表示できましたので実装してPR作りますね

**Comment by KisaragiEffective** [comment]
implemented by #1296
