### ISSUE TITLE
Minestackのアイテム個数表示にカンマをつける

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1236]
https://redmine.seichi.click/issues/10282
第16回アイデア会議にて承認された

**Comment by KisaragiEffective** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/aea16ce7a4f8d8b631d0bd345be591b887c8b655/src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala#L83

**Comment by KisaragiEffective** [comment]
assigned to: @Siro256
