### ISSUE TITLE
所有者表記削除システムが機能していない

### ISSUE THREAD

**Issue by LargoGreenTea** [GiganticMinecraft/SeichiAssist#1249]
検証内容：
  棒メニュー２ページ目の所有者表記削除システムにアイテムを投入し、予想した動きをするかを確かめる

予想した動き：
  所有者表記があるものを入れた際は所有者表記が「なし」に変更されたものが返り、所有者表記がないものはそのままプレイヤーの手元に帰ってくる

実際の動き：
　所有者名義の有無に関わらず、アイテムが帰ってこない。（ゴミ箱のようにアイテムが消える）

コード：
https://github.com/GiganticMinecraft/SeichiAssist/blob/develop/src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala

**Comment by KisaragiEffective** [comment]
そもそもアイテムを返すコードが記述されていない。

**Comment by Lucky3028** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/8c66a4e61e197efe54d6a84a35ae47f3c4be9fae/src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala#L618
ここは違うんですか…?

**Comment by kory33** [comment]
> https://github.com/GiganticMinecraft/SeichiAssist/blob/8c66a4e61e197efe54d6a84a35ae47f3c4be9fae/src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala#L618
> 
> 
> ここは違うんですか…?

これ、実行できてないですね(これは純粋関数で、戻り値の型は `Kleisli[IO, Player, Unit]` ですので、 `Player` を渡したうえで `run` する必要があります)

**Comment by KisaragiEffective** [comment]
まだ機能してない！

**Comment by rito528** [comment]
そもそも今、所有者表記削除システムってあるんですか？

**Comment by Lucky3028** [comment]
GTなどの名義表記を消す方向にあるので、あるはずです

**Comment by rito528** [comment]
見当たりませんね.....

**Comment by Lucky3028** [comment]
まじ？じゃあ作り直しますか

**Comment by rito528** [comment]
そもそも実装されておらず、bugではないのでclose
このアイデアはアイデア会議に差し戻し。
