### ISSUE TITLE
アサルトスキル切替時のメッセージの色を変える

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1270]
https://redmine.seichi.click/issues/10297
[第17回アイデア会議](https://redmine.seichi.click/issues/10288)にて承認されたアイデア。

**Comment by KisaragiEffective** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/2358eb91fed4f9628599e89a93cc18715e88bfca/src/main/scala/com/github/unchama/seichiassist/seichiskill/assault/AssaultRoutine.scala#L168
https://github.com/GiganticMinecraft/SeichiAssist/blob/2358eb91fed4f9628599e89a93cc18715e88bfca/src/main/scala/com/github/unchama/seichiassist/seichiskill/assault/AssaultRoutine.scala#L185

この`${GOLD}`のところを変えるとよい
