### ISSUE TITLE
プレミアムエフェクト機能全般が使用不可

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#137]
運営チームへのお問い合わせより。

棒メニューのプレミアムエフェクトについて
- 以前解除したが、岩盤に戻っている
- プレミアムptが以前の状態に戻っている
- 解除を押してもエフェクトが解除されない
- ↑ただし購入履歴には残っている

関連 #103

**Comment by kory33** [comment]
これマイグレーション漏れでしょうか（なんでだろう）

**Comment by unchama** [comment]
問い合わせより
先日のプレミアムエフェクトについての追加点
・再起動を挟むとptが戻っている(昨日は20pt→今日は30pt)
・しかし、購入履歴にはちゃんと残っている

**Comment by kory33** [comment]
🤔

**Comment by kory33** [comment]
これ直ったら1.1.1としてリリースするべきぽい
