### ISSUE TITLE
各種メニューのページ送り・戻りの不具合

### ISSUE THREAD

**Issue by karayuumac** [GiganticMinecraft/SeichiAssist#14]
時々、各種メニューのページの送り・戻りが出来なくなる事がある。大変利便性が悪い。
これはAPIの制限によりページの送り・戻りのボタンとして使用している頭が読み込めなくなってしまうためである。

以下が現在使用しているコード。getOwner()で正しいOwnerが取得できなくなる事が原因である。
``` java
itemstackcurrent.getType().equals(Material.SKULL_ITEM) && ((SkullMeta)itemstackcurrent.getItemMeta()).getOwner().equals("MHF_ArrowRight")
```
これを読み込みの成否にかかわらず、使用できるようにしたい。

**Comment by unchama** [comment]
どの辺りのコミットからかわかりませんが、ページ遷移が全くできなくなってしまっている気がします。。。

**Comment by kory33** [comment]
Mostly fixed on 1.1.2.
