### ISSUE TITLE
SeichiExpAmountのドキュメントが古い

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#1508]
https://github.com/GiganticMinecraft/SeichiAssist/blob/3411b420a236b19b7d15afe7632dbacbcb23eb81/src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/domain/level/SeichiExpAmount.scala#L9

とあるが、SeichiExpAmountを生成する方法が`ofNonNegative`しかない。メソッド名から推論されるように、この作成方法は負の値を許さない。

ドキュメントを更新するべき。

**Comment by rito528** [comment]
このドキュメントの`非負の値に対応する`と`負の値を許さない`というのは同じ意味な気がしますが...?

**Comment by KisaragiEffective** [comment]
同じ意味ですね、すみません
