### ISSUE TITLE
文字化けしたメッセージが送られる

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#154]
そもそもSeichiAssistの問題なのか、という時点から調査が必要
[参考画像](https://cdn.discordapp.com/attachments/237758724121427969/581706979819388938/2019-05-25_13.55.14.png)
(日付のようなメッセージが文字化けして送られている)

**Comment by KisaragiEffective** [comment]
https://gyazo.com/2643433107762c91f55d44a7a398e599

**Comment by unchama** [comment]
サーバログイン時のメッセージ表示は別プラグインを使用していますので、こちらはクローズしておきます。
