### ISSUE TITLE
/presentコマンドの一部をコンソールからでも実行できるようにする

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1589]
* delete
* grant
* revoke

**Comment by rito528** [comment]
パッと見た感じ/presentコマンドはすべて`playerCommandBuilder`を利用してコマンドを組み立てられているので、コンソールから実行したいコマンドを`ContextualExecutorBuilder.beginConfiguration()`に変えればできそうです
