### ISSUE TITLE
整地レベルアップでガチャ券を報酬として配布する機能の追加

### ISSUE THREAD

**Issue by karayuumac** [GiganticMinecraft/SeichiAssist#16]
Lv50までの初心者を対象として、レベルアップ時に段階的に報酬(ガチャ券)を用意するというもの。
既にそのレベルを超えているプレイヤーにも受け取れるようにする。

**Comment by Lucky3028** [comment]
#740 にて、「レベルアップでガチャ券を報酬として配る」はできたが、「既にそのレベルを超えているプレイヤーにも受け取れるように」はできていない

**Comment by Lucky3028** [comment]
というかLv.50までやんけ！！！

**Comment by Lucky3028** [comment]
「既にそのレベルを超えているプレイヤーにも受け取れるように」ってどうすればいいんでしょう...？わざわざフラグ作るまでもないですよね...

**Comment by KisaragiEffective** [comment]
close per #799.
