### ISSUE TITLE
中秋の日の日付を毎年変更する

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1624]
[実績9037](https://github.com/GiganticMinecraft/SeichiAssist/blob/02b1b0a073f3a303dc1237c3ac02c196658d4064/src/main/scala/com/github/unchama/seichiassist/achievement/SeichiAchievement.scala#L323)は中秋の名月の日に解放されることを想定されている。これは旧暦の8/15なので、本来は自動的にこれを計算するようにするべきだが、旧暦と新暦の変換式が出てこないので、毎年手動で変更する必要がある。

**Comment by KisaragiEffective** [comment]
実は暦というのは私達が思っているよりも百倍厄介な代物なので、good first issueとは言い難い。

**Comment by Lucky3028** [comment]
単純に日付の数字変えればいいので...

**Comment by kory33** [comment]
旧暦の日付返せるライブラリ使うと一発だったりしませんか？

**Comment by Lucky3028** [comment]
なるほど

**Comment by Lucky3028** [comment]
https://qiita.com/niwasawa/items/10a9a62affdb8b733507
ここらへんがあった
