### ISSUE TITLE
OpenJDKのDockerイメージがDeprecatedになっている

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1668]
https://hub.docker.com/_/openjdk

**Comment by Lucky3028** [comment]
@kory33 @KisaragiEffective どれにしておきます？

**Comment by kory33** [comment]
切り替えるなら特にこだわりは無いので `eclipse-temurin` で良いと思います

イメージ切り替えのタイミングについてですが、本番環境がまだベアメタル openjdk のままのはずなんで、そこの移行をするタイミングで切り替えたさはあります(今切りかえても問題は無いと思いますが、念の為？)

**Comment by KisaragiEffective** [comment]
何もわからないので私はパスで

**Comment by Lucky3028** [comment]
> そこの移行をするタイミングで切り替えたさはあります

その移行はどのタイミングで行うことを想定していますか？

**Comment by kory33** [comment]
> > そこの移行をするタイミングで切り替えたさはあります
> 
> その移行はどのタイミングで行うことを想定していますか？

Spigot サーバーが Docker に乗るのと同タイミングを想定しています。その際にはおそらく `itzg/minecraft-server` が利用している JDK のベースイメージを SeichiAssist のデバッグでも使うことになるかなと思います（もしくは、 `itzg/minecraft-server` を SeichiAssist のデバッグで使ってしまっても問題ないかもしれません）
