### ISSUE TITLE
Bungeecordの開発用Docker imageがBuildに失敗する

### ISSUE THREAD

**Issue by haruyan-hopemucci** [GiganticMinecraft/SeichiAssist#1673]
2022.10.15現在、bungeecord_1およびbungeecord_2コンテナをbuildする際に `RUN mvn clean install ` が失敗してコンテナのビルドができなくなっています。

## 原因

上記mvnコマンドは `minecrafter/RedisBungee` のビルドタスクですが、ビルド中の自動テストでmojangの公開外部APIにアクセスしています。（`https://api.mojang.com/user/profiles/<uuid>/names`) API通信疎通のテストをしているようです。
このAPIが2022.9.13付けで廃止されました。現在このAPIはエラーメッセージをJSONで返すようになっています。

[Username History API Removal FAQ ](https://help.minecraft.net/hc/en-us/articles/8969841895693-Username-History-API-Removal-FAQ-)

テストクラス内で期待しているJSONの構造とエラーメッセージの構造が異なるため、JSONのデコードに失敗しているのがテスト失敗の原因となっている模様です。

## 対処法

タスクに自動テストをスキップするオプション `RUN mvn clean install -DskipTests=true` を付与することでテストの実行を回避すればコンテナのビルドは可能です。ただし必要なテストもスキップされますし、当該APIをたたくメソッドはそのまま残っているため
このメソッドをコールすると結局エラーになってしまいます。

何かクリティカルな現象が起こらない限りは個人の開発環境はテストスキップでしのげるとは思いますが、本番環境でも同じ現象が起こりえると思われるのでその際は何らかの根本対策が必要かもしれません。

**Comment by haruyan-hopemucci** [comment]
FYI:
現在リポジトリのコンテナで使用しているRedisBungeeは事実上メンテナンスが放棄され、spigotのサイトでダウンロードできるRedisBungeeは違うユーザーがfolkして引き続き開発しているもののようです。
https://www.spigotmc.org/resources/redisbungee.87700/
https://github.com/ProxioDev/RedisBungee
互換性があるならこちらのRedisBungeeに乗り換えるのもアリなのでしょうか。

なお、9月に廃止されたAPIの対策は特に行っていないようです。
件のAPIを叩くテストが存在しないため、気づいていない可能性があります。（APIのアクセスで例外が起こっても握りつぶしてしまう実装のため）

**Comment by haruyan-hopemucci** [comment]
試しに RdisBungeeを https://github.com/ProxioDev/RedisBungee の最新stableバイナリ(0.7.3)に差し替えて開発コンテナで動作させてみたところ、特に致命的なエラーが発生するような様子はありませんでした。
readmeにも後方互換性は確保していると書かれていますし、十分に動作検証ができればProxioDev版に変更しても良いのではないでしょうか。jarで提供されているのでビルドも必要なくなります。

**Comment by KisaragiEffective** [comment]
一般的に変更の規模と破壊的変更がないかどうか確認する+何かあったときのコストというのは比例します。この問題を解決するためだけにフォークに乗り換えるのは私は消極的です。

**Comment by rito528** [comment]
RedisBungeeを使わなくてもよい方向に持っていきたいですねという気持ちがあります

**Comment by rito528** [comment]
closed by #1787
