### ISSUE TITLE
初期装備の棒の名前を変える

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#1676]
https://redmine.seichi.click/issues/11331
[第26回アイデア会議](https://redmine.seichi.click/issues/11202)にて承認されたアイデア。

rel. GiganticMinecraft/SeichiAssist#1644

**Comment by Lucky3028** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/451e430c21c9e0b47cbe948e10f7accebae7caf7/src/main/scala/com/github/unchama/seichiassist/listener/PlayerJoinListener.scala#L120

この`ItemStack`に`setItemMetaすればよい`

**Comment by Lucky3028** [comment]
cf. https://github.com/GiganticMinecraft/SeichiAssist/pull/1655/files
