### ISSUE TITLE
エデンサーバーに参加した場合に警告を表示する

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1695]
cf. https://discord.com/channels/237758724121427969/237761024659423234/1023570687564193822

**Comment by haruyan-hopemucci** [comment]
引き受けます

警告を表示する場所は通常のチャット欄で良いでしょうか。
文面はdiscordのお知らせを要約し、「ご利用は自己責任で」のような内容で良いのかな。PR時に推敲お願いできればと思います。
