### ISSUE TITLE
二つ名選択メニューの戻るボタンの不具合

### ISSUE THREAD

**Issue by karayuumac** [GiganticMinecraft/SeichiAssist#17]
二つ名システムのメニューにおいて、２ページ目から１ページ目へ戻るボタンが表示されない。

**Comment by kory33** [comment]
いつのまにかfixされています

**Comment by kory33** [comment]
と思ったらあれですね、二つ名のパーツ選択でメインメニューへ、だけが表示されてページを戻れないというUI上の不具合ですね

**Comment by kory33** [comment]
fixed in #333
