### ISSUE TITLE
ガチャを引いたときに大当たりアイテムが排出されてもGTアイテム判定がされてしまう

### ISSUE THREAD

**Issue by rito528** [GiganticMinecraft/SeichiAssist#1700]
https://github.com/GiganticMinecraft/SeichiAssist/blob/758997df9c790dac934805f257644a16b0ded8d1/src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/GachaRarity.scala#L26
のfilterの処理がおかしそうですが、原因不明です

**Comment by haruyan-hopemucci** [comment]
filterの処理は間違っていないと思います。
問題なのは、`GachaRarity`で列挙している各レアリティの`maxProbability`だと思われます。
本番の抽選確率が開発用SQLで投入するガチャデータの抽選確率と同じであれば、例えば天叢雲剣は排出率0.001(0.1%)となっています。他の大当たり景品も同様に0.001で設定されています。
Gigantic大当たり品は0.0001（アーサーはさらに1/10の0.00001）で設定されています。
対してGachaRarityにおけるGiganticに設定されているmaxProbabilityは、
```scala
case object Gigantic extends GachaRarity(GachaProbability(0.001))  // <- 0.1%
```
になっており、大当たり品がGigantic判定になってしまっています。
`GachaRingoOrExpBottle`以外のmaxProbabilityを全て1/10にすれば期待通りのメッセージが出ると思います。
（実際にやってみたら表題の現象は解消されました）

ただ、`maxProbability`の意味合いは「そのカテゴリーに属するアイテム全体の排出確率」ということだと思うので、`gachaPrize.probability`と比較することが意味合いとしてどうなんだろうか、とは感じます。

**Comment by kory33** [comment]
>  問題なのは、`GachaRarity`で列挙している各レアリティの `maxProbability` だと思われます。 

[元の実装](https://github.com/GiganticMinecraft/SeichiAssist/pull/1502/files#diff-ae0e03cef3d7ace0f372f4968793feff9a82f1ece08202f2f806212d502b6722L225-L293) を確認してみたところ、閾値が `Gigantic = 0.001`, `Big` が `0.01` というのは正しそうです。

> ただ、`maxProbability`の意味合いは「そのカテゴリーに属するアイテム全体の排出確率」ということだと思うので、`gachaPrize.probability`と比較することが意味合いとしてどうなんだろうか、とは感じます。

`val r: GachaRarity` があった時の `r.maxProbability` は、「`r` がレアリティになるガチャアイテムの出現確率の最大値」(集合の記法で書けば、 `max { prize.probability | prize: GachaPrize, rarity of prize is r }`) であるというのが現在のモデルの意図であると理解しています。元のコードは `<=` ではなくて `<` で比較しているので、このモデルが間違っていそうですね。

`probabilityUpperLimit` みたいな曖昧な命名にしておいて、docコメント側で意図 (つまり、 `probabilityUpperLimit` とガチャ景品のレアリティがどのような関係にあるのか) を説明するのが良さそうに思えます。
