### ISSUE TITLE
/gacha getコマンドで、記名する名前を指定できることになっているが、実際には指定できない

### ISSUE THREAD

**Issue by rito528** [GiganticMinecraft/SeichiAssist#1704]
実際には必ずコマンドを発行したプレイヤーの名前が記名されている
https://github.com/GiganticMinecraft/SeichiAssist/blob/3558a3aea6c8abecf5ff1a5058c69ed7bde47967/src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/command/GachaCommand.scala#L189

**Comment by haruyan-hopemucci** [comment]
Luckyさん曰く、運営のみ使用できるコマンドなので、
- サーバー内のプレイヤーの名前であるかどうかのチェックは必要ない
- 文字種、文字数制限も必要ない
とのことです。
