### ISSUE TITLE
ホームメニューのホームポイント削除確認画面でホーム名称が表示されない

### ISSUE THREAD

**Issue by haruyan-hopemucci** [GiganticMinecraft/SeichiAssist#1708]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/68041476/199304926-a30a79c9-3c5a-4a94-8e02-d8f0fd949cd4.png">
を削除しようとすると、
<img width="536" alt="image" src="https://user-images.githubusercontent.com/68041476/199305062-23e6d5b2-cf5d-4c62-adc7-bdb908f9fa4b.png">
名称が空白です。

当該箇所のコードを確認してみると、ホーム名を取得する処理が抜けているようです。

**Comment by Lucky3028** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/3558a3aea6c8abecf5ff1a5058c69ed7bde47967/src/main/scala/com/github/unchama/seichiassist/menus/HomeMenu.scala#L151
