### ISSUE TITLE
/gacha getコマンドで、アイテムID=0を指定できない

### ISSUE THREAD

**Issue by haruyan-hopemucci** [GiganticMinecraft/SeichiAssist#1736]
`/gacha get`コマンドの説明にて、

```text
        s"$RED/gacha get <ID> (<名前>)",
        "指定したガチャリストのIDを入手 (所有者付きにもできます) IDを0に指定するとガチャリンゴを入手できます",
```

と記載されているが、ID 0 を指定できません。parserで1以上の整数を指定するよう制限がかかっています。
また、ID 0 が指定できるようになったとしても、`指定されたIDのアイテムは存在しません！`と表示されてがちゃりんごが入手できません。（これはおま環かもしれません。gachadataテーブルにID:0のデータが入っていれば問題なし？）

**Comment by rito528** [comment]
普通に実装ミスです😇😇
がちゃりんごはハードコーディングされているのでそこから取得するようにしたいです
