### ISSUE TITLE
BuildAssistをSeichiAssistに吸収合併させる

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#178]
BuildAssistはSeichiAssistのリファクタリングのたびに動かなくなる程にSeichiAssistに依存してしまっているためプラグインを分けている意味がない。
https://github.com/GiganticMinecraft/BuildAssist

**Comment by kory33** [comment]
草

**Comment by unchama** [comment]
(戦略的M&Aだ… )
