### ISSUE TITLE
Minestackにどのアイテムも収納されず消える

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#1834]
`ListExtra.rePrepend`のpredicate（`_.mineStackObject == mineStackObject`）がfalseになっているので、`ListExtra.rePrepend`の中の`find`が`None`になって処理が行われない

https://github.com/GiganticMinecraft/SeichiAssist/blob/98cbe4f573cf9c55793d5ede81b43c1398e8290b/src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/BukkitMineStackRepository.scala#L39-L40

https://github.com/GiganticMinecraft/SeichiAssist/blob/98cbe4f573cf9c55793d5ede81b43c1398e8290b/src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/BukkitMineStackRepository.scala#L51-L52

**Comment by Lucky3028** [comment]
@rito528 さんがおっしゃるには、以下で`map`しているからではないかということで、`Ref[G, ...]`を返すようにすればいいのでは？ということ
https://github.com/GiganticMinecraft/SeichiAssist/blob/98cbe4f573cf9c55793d5ede81b43c1398e8290b/src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/System.scala#L103-L105

**Comment by Lucky3028** [comment]
なにもわからない...

**Comment by rito528** [comment]
現在の実装では直せなさそうなので、minestacksystemをminestacksystemのsubsystemとして切り出す必要がありそうです。(多分これで`mineStackObjectRepository`を`map`せずに返せるようになりそう)
(minestackという巨大なシステムを一つのSystemで管理するというのが間違いっぽい)

**Comment by rito528** [comment]
リアルが落ち着いたらやります

**Comment by rito528** [comment]
いろいろ試してみたんですが原因は違いそうで、ローカル環境でサーバーを起動するとアイテムが収納されないんですが、デバッグサーバーで検証するとアイテムが収納されるようです....

**Comment by Lucky3028** [comment]
？？？

**Comment by Lucky3028** [comment]
そんなことあります？
