### ISSUE TITLE
バレンタインイベントのクッキーを召喚できるコマンドを追加する

### ISSUE THREAD

**Issue by mel9y** [GiganticMinecraft/SeichiAssist#1872]
- `/event valentine` でクッキーを召喚できるコマンドを追加する

https://github.com/GiganticMinecraft/SeichiAssist/blob/b62f60297a8183d0401f7d6f232919c337747a5d/src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/commands/EventCommand.scala#L42-L50

**Comment by m2en** [comment]
意気揚々とassignしたけども他の人がやってもいいですよの看板を首から下げて待ってます

**Comment by Lucky3028** [comment]
むしろお仕事始めたてみたいなノリで、めるさんがやっていただいてまったく構いませんの看板を持っています
