### ISSUE TITLE
バレンタインイベントで扱われるチョコチップクッキーの名前を区別する

### ISSUE THREAD

**Issue by mel9y** [GiganticMinecraft/SeichiAssist#1910]
バレンタインイベントで扱われる二種類のチョコチップクッキーは名前に違いがなく、判別するのが名義システムがあるかないかになってしまっている

1. イベント期間中のログイン時に配布されるチョコチップクッキー (ブログ記事では ② と案内されているもの)
2. クリーパー自身の爆発もしくはクリーパーの爆発に他Mobを巻き込んだ際にドロップするチョコチップクッキー (ブログ記事では ① と案内されているもの)

そこで、限定ヘッドとの交換でも用いられる2番のチョコチップクッキーの名前を変更して、わかりやすく区別したい

- [x] チョコチップクッキーの名前変更案を決める

→ **爆発したカップルの本命チョコチップクッキー**

- [ ] SeichiAssist 側を変更する

なお、現在(2023/02/22)はイベント期間中で、この変更が行われたまま本番環境にリリースされると村人との交換に支障をきたすため、変更はイベント終了後に行う

**Comment by Lucky3028** [comment]
- 爆発したリア充の持ち物
- Happy Valentine

とかが素直でいいのでは

**Comment by m2en** [comment]
> 爆発したリア充の持ち物

好き

**Comment by m2en** [comment]
爆発したカップルの本命チョコ のほうがスッキリ感がある...?

**Comment by Lucky3028** [comment]
ええやん(ええやん)
