### ISSUE TITLE
ギガンティックバーサークのレベルがリセットされている

### ISSUE THREAD

**Issue by m2en** [GiganticMinecraft/SeichiAssist#1922]
https://discord.com/channels/237758724121427969/1080138409428918292

> ギガンティックバーサークのスキルがリセットされています。
> このアカウントは、完成済みのはずですが、初期ステータスに戻っています

![image](https://user-images.githubusercontent.com/82575685/222071376-26cf6765-fb5f-4096-a404-bdc96c65e138.png)

**Comment by m2en** [comment]
> こちらに関して、リログするたびにリセットされます

**Comment by rito528** [comment]
closed by #1923
