### ISSUE TITLE
葉(全種)ブロックの直列設置が自然消滅するほうの葉ブロックになっている

### ISSUE THREAD

**Issue by ghost** [GiganticMinecraft/SeichiAssist#1933]
> 本来葉ブロックは置くと消えません。
> ですが直列設置で設置される葉ブロックは
> 自然消滅するほうの葉ブロックになっています。
> この現象は恐らく直列設置が実装された当時からずっと残っていると思われます。

報告者: [Plastics777](https://discord.com/channels/237758724121427969/1087769150836977735/1087769150836977735)

**Comment by lis2a** [comment]
直列配置のブロックを自然消滅しない方に変えれば直るかも？ good first issue でもいいかも (コード読んでいないので憶測です)
