### ISSUE TITLE
分割可能なfor-eachを並行処理する

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#194]
1. まずプロファイルする (e.g. onDisable時のブロック強制全破壊に何秒かかったか) -> measureMiliSecondsで可能
2. その上で、分割不可能な副作用 (e.g. findFirst)を用いていないループについて、特に時間がかかっているもの (e.g. 数十秒)を、複数のコルーチンを用いてタスクを分割できないか検討する (このときの分割の手法として、タスク数による等分割、または実行時間による等分割が考えられるが、大体のオペレーションはO(1)や係数があまり発散しないO(n)で済むと考えられるので、等分割を主に考える)
3. 並列処理して実行時間が短くなるfor-eachをSkedularやGlobalScope.launchを用いて分割する (タスクの数に応じて並列/シングルスレッドに切り替えることを想定)

**Comment by kory33** [comment]
timings pasteでブロッキングしている箇所等を見てパフォーマンスが悪い場所があった場合修正するというのをしています。今のところほとんど問題はなさそうです。
