### ISSUE TITLE
一括クラフトの6ページ目が欠落している

### ISSUE THREAD

**Issue by lis2a** [GiganticMinecraft/SeichiAssist#2055]
> 一括クラフトの5ページ目に｢6ページ目へ｣のボタンがありますが
> 6ページ目には何もありません
> ![image](https://github.com/GiganticMinecraft/SeichiAssist/assets/82575685/f0f567e4-66d4-4da2-a1de-51cdce88f842)
> ![image](https://media.discordapp.net/attachments/1111478751239360673/1111478751931408404/2023-05-26_09.45.56.png?width=1320&height=1132)
> Report by [x256x](https://discord.com/channels/237758724121427969/1111478751239360673/1111478751239360673)

**Comment by kory33** [comment]
6ページ目は [存在している](https://github.com/GiganticMinecraft/SeichiAssist/blob/5b5936b4d09ca06028cdbfa694a34606d51fe704/src/main/scala/com/github/unchama/buildassist/menu/MineStackMassCraftMenu.scala#L607) ので、描画に失敗していると考えるのが妥当っぽい

**Comment by lis2a** [comment]
タイトル変えとくか
