### ISSUE TITLE
ImmutableListFactory.of(Vararg<E>)の仕様違反

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#208]
add(E)はできないがset(int, E)はできてしまう

**Comment by kory33** [comment]
Javaの`List`はinterfaceレベルで`set`が付いているので全部KotlinのRead-onlyな`List`に置き換えるべきかなと思います

**Comment by KisaragiEffective** [comment]
残念ながらkotlinのListもReadOnlyなだけなので完全にイミュータブルではありません。。。
具体的に言うと、MutableListにListのビューを代入してMutableListを操作するとListのビューが書き換わってイミュータビリティが崩れるからです。
まあそもそもそんなことするのがおかしいで片付ければそれまでなんですけど(

**Comment by kory33** [comment]
それはそんなことをする方が悪いで片づけてよいと思います（そもそも原理的に改変不可であるというとこまで求める状況はあまりないですし）
いずれにせよJavaの`List`はそもそもイミュータブルであることを想定していなさそうですのでKotlinの`List`に置き換えるべきかなと思います。

**Comment by KisaragiEffective** [comment]
> いずれにせよJavaのListはそもそもイミュータブルであることを想定していなさそうですのでKotlinのListに置き換えるべきかなと思います。
はい
余談: コレクションフレームワークが導入された1998年当時は、イミュータブルの概念そのものはあまり浸透していなかったようです。
