### ISSUE TITLE
デバッグサーバーを立ち上げるとMySQLが警告メッセージを表示する

### ISSUE THREAD

**Issue by aqyuki** [GiganticMinecraft/SeichiAssist#2082]
![スクリーンショット 2023-06-08 201432](https://github.com/GiganticMinecraft/SeichiAssist/assets/117277631/9ba315f4-cbeb-4c95-9813-bb7e997ba0f7)

prepare-docker.shを利用して開発用サーバーを立てた際にseichiassist-db-1がエラーを出力しています。
エラーを出力していますが、プラグイン側でなにか不具合が発生する等は今のところ確認していません。
Release v80以前は発生しておらずv80のリリースが行われたあともしばらくは発生していなかったと思います。

環境:
* Ubuntu 22.04.2 LTS
* Docker 24.0.2 build cb74dfc

**Comment by aqyuki** [comment]
追記です。
* コンテナのキャッシュを削除しての再実行
* 再クローン
を試しても治りませんでした。

**Comment by lis2a** [comment]
こっちの環境では何もエラーを吐かないな
立ち上げた瞬間吐く感じですか？

**Comment by rito528** [comment]
@aqyuki 
MariaDBの[docker volumeの削除](https://qiita.com/Ikumi/items/b319a12d7e2c9f7b904d)は試しましたか？

**Comment by rito528** [comment]
多分なんですが、エラーログを見る限り[MariaDBのバージョンアップ](https://github.com/GiganticMinecraft/SeichiAssist/commit/93e9e9743ca00b0e0f81a64448677ce73fda57a9)の影響なので、ごちゃごちゃ作業をするよりもMariaDBのデータを初期化するのが早いと思います。

**Comment by aqyuki** [comment]
> @aqyuki MariaDBの[docker volumeの削除](https://qiita.com/Ikumi/items/b319a12d7e2c9f7b904d)は試しましたか？

治りました。　ありがとうございます。
