### ISSUE TITLE
CI: The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#2133]
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by KisaragiEffective** [comment]
@Lucky3028 せめてどのCIで起こったことなのか書いていただけないと誰も直しようがありません

**Comment by Lucky3028** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/actions/runs/5412918402
ここです。リリースのPRつくってるところですね
