### ISSUE TITLE
ガチャをまとめて引くボタンの説明文の色がデフォルトのままになっている

### ISSUE THREAD

**Issue by rito528** [GiganticMinecraft/SeichiAssist#2180]
この色は何も指定しなかったときの色なので、多分実装時に変え忘れているものです。

![image](https://github.com/GiganticMinecraft/SeichiAssist/assets/39003544/58ede8d7-8fba-41cd-b1a0-71a459199311)

**Comment by m1sk9** [comment]
ボタンの説明として使われている Lore を定義しているのはここ。

https://github.com/GiganticMinecraft/SeichiAssist/blob/e61ac465e8d884740a3cbf30a7fd4513790eb9a9/src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala#L391-L396

このように `$RESET${DARK_GRAY}` を指定してやることで他のボタンの Lore と同じにすることができます。

https://github.com/GiganticMinecraft/SeichiAssist/blob/e61ac465e8d884740a3cbf30a7fd4513790eb9a9/src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala#L414-L419
