### ISSUE TITLE
チェスト破壊/ネザー水晶類破壊フラグ設定をトグルできない

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#2197]
- パッシブスキルである「チェスト破壊スキル」や「ネザー水晶類破壊スキル」がトグルできない
- DBを見ると、トグル設定を保存するテーブルが空のままなので、DBへの書き込みもされていない
- したがって、常に初期値のまま
- トグルをした旨のメッセージは表示されている

**Comment by Lucky3028** [comment]
@KisaragiEffective 正確にはオン・オフもできないので、「オフにしても」は違うと思います。

**Comment by rito528** [comment]
明日起きたらやります

**Comment by rito528** [comment]
コードを読んだ結果

DBへの書き込みはされていて、単純にフラグの反転処理をしていなかったことが原因でした
