### ISSUE TITLE
整地ワールドで複数種類同時破壊スキルをOFFにして連続系スキル・遠距離系スキルを使用すると(強制ONにもかかわらず)OFFになってしまう

### ISSUE THREAD

**Issue by Siro256** [GiganticMinecraft/SeichiAssist#221]
(#質問-非公式より)
https://ptb.discordapp.com/channels/237758724121427969/430346786717171725/613592780236652556

「複数種類同時破壊スキルをオフにした状態でトム・ボウイ系統の連爆系スキルを使うと、整地ワールドにもかかわらず、複数種類同時破壊スキルが動かないような状態になります。」

**Comment by karayuumac** [comment]
遠距離系スキルでも同様に複数種類同時破壊が働かないもよう。

**Comment by kory33** [comment]
すでに直っている模様
