### ISSUE TITLE
[1.18] `Material` に対する match を error にする Scalafix rule を書く

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#2226]
https://github.com/GiganticMinecraft/SeichiAssist/pull/2115 にて露呈した問題で、1.13 以降の Spigot API では [`org.bukkit.Material`](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html) の case 数が 1800 個を超えており、`t: Material` について `t match { ... }` と書くだけでコンパイル時間が 200 秒ほど増える現象が発生していた。

このため、`org.bukkit.Material` が scrutinee に来る `match` 式は Scalafix rule にてエラーとしたい (少数のそのような `match` が紛れ込んだ場合、数分程度コンパイル時間が伸び、気づかないことがありそうなので)。

**Comment by KisaragiEffective** [comment]
んなことある？？？？？

**Comment by KisaragiEffective** [comment]
メモ: 帰ったらプロファイル結果を貼る

**Comment by kory33** [comment]
@KisaragiEffective 

> メモ: 帰ったらプロファイル結果を貼る ついでに精査してscala/bugに上げる

#2115 で入ってる d7cdb12f0b6b4a8f6337aa797726cddd93d73ca2 で Chrome Trace 生成するようにしたんで、 `sbt compile` するだけでプロファイル結果が生成されるようにはなってます

**Comment by kory33** [comment]
（昨日軽くデバッガーで scalac の様子を覗いてたんですが、match optimization で unreachable arm の存在を調べるために明大論理ソルバを持ち出しているっぽくて、そこで無限に時間が掛かっていました　普通に想定していない大きさの `enum` という説はある）

**Comment by KisaragiEffective** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/pull/2115/commits/1ad23ea5d778192470c10a95e7049f0920adad42

↑OnClickTitleMenuとBreakUtil.isAffectedByGravityはまぁ仕方ないだろうという気持ちになるが、それ以外は自明なパターンなので意味不明

**Comment by KisaragiEffective** [comment]
最小化するため、試しに

```java
enum Hello {
    E1,
    /* ... */
    E2000
}
```

```scala
object App {
    def main(args: Array[String]): Unit = {
        val x: Hello = Hello.E1
        x match {
            case Hello.E4 => println("E4")
            case _        => println("other")
        }
    }
}
```

という例を持ち出したら普通に4分程度かかった。`sbt clean; compile`をして上記コードをコンパイルした結果、`scala.tools.nsc.transform.patmat.PatternMatching$OptimizeMatchTranslator.{unreachableCase,exhaustive}`がCPU時間の99.9%を占めていたので`match`関連なのは間違いない。

**Comment by KisaragiEffective** [comment]
@kory33 

> （昨日軽くデバッガーで scalac の様子を覗いてたんですが、match optimization で unreachable arm の存在を調べるために明大論理ソルバを持ち出しているっぽくて、そこで無限に時間が掛かっていました　普通に想定していない大きさの `enum` という説はある）

もしかして: 命題論理ソルバ？

**Comment by KisaragiEffective** [comment]
> 最小化するため、試しに
> 
> ```java
> enum Hello {
>     E1,
>     /* ... */
>     E2000
> }
> ```
> 
> ```scala
> object App {
>     def main(args: Array[String]): Unit = {
>         val x: Hello = Hello.E1
>         x match {
>             case Hello.E4 => println("E4")
>             case _        => println("other")
>         }
>     }
> }
> ```
> 
> という例を持ち出したら普通に4分程度かかった。`sbt clean; compile`をして上記コードをコンパイルした結果、`scala.tools.nsc.transform.patmat.PatternMatching$OptimizeMatchTranslator.{unreachableCase,exhaustive}`がCPU時間の99.9%を占めていたので`match`関連なのは間違いない。

tracked: https://github.com/scala/bug/issues/12873

**Comment by KisaragiEffective** [comment]
closed by #2227

**Comment by KisaragiEffective** [comment]
`(scrutinee: @unchecked)`もワークアラウンドになるらしいが、やりたくないなぁという気持ち
