### ISSUE TITLE
MebiusのTipsが読み込めていない

### ISSUE THREAD

**Issue by soundofhorizon** [GiganticMinecraft/SeichiAssist#235]

**Comment by KisaragiEffective** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/238400d25003e4aba43ba004d4fe956ec567bde8/src/main/java/com/github/unchama/seichiassist/listener/MebiusListener.java#L668

**Comment by karayuumac** [comment]
https://seichi.click/wiki/Tips
これのリンク切れによるもの。滅多に変更されるものではないと思うので、べた書きします。
