### ISSUE TITLE
`/gacha save`コマンドを削除し、説明文も消す

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#2352]
すでに不要なため

`/gacha add`時に表示される「`/gacha save`を実行してください」という旨のメッセージや`/gacha help`のヘルプメッセージからも消す

**Comment by rito528** [comment]
これ、コード上にこのメッセージが見当たらないので develop ブランチではすでに削除されていそう

**Comment by Lucky3028** [comment]
ありがとうございます。
