### ISSUE TITLE
デバッグ鯖バグカバレッジ

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#243]
- [x] 整地量が増えない (by @soundofhorizon) (EDIT: fixed by 09748b0)
- [x] アクティブスキルブックをクリックしたときの音が鳴らない (by @soundofhorizon) (EDIT: fixed by 79a158b)
- [x] ネザーとENDでは掘ることが出来ない [図1](https://gyazo.com/f60346c866bb8b15ba7be5b8d6459bde) (by @soundofhorizon) (EDIT: SeichiAssistの問題ではない - ![図1b](https://i.gyazo.com/019ce084df36d214a13aab9e20b78e8f))
- [x] ガチャ券が配布されない [図2](https://gyazo.com/97ae66df213f7d413b7466d22a64b5e1) (by @soundofhorizon) (EDIT: fixed by 40b2434)
- [x] 鉱石交換で交換券が配布されない [図3](https://gyazo.com/9ea55bf812dc7eaa629bc6ba2df8c8b3) (by @soundofhorizon) (EDIT: fixed by 2483c74a)
- [x] カラーコードがおかしい [図4](https://gyazo.com/39e43e5f69322bcf945646770fa50b5d)  (by @soundofhorizon) (EDIT: fixed by 737a480)
- [x] 二つ名設定メッセージに意図しない改行が入っている [図5](https://gyazo.com/3c13101b3c18475f289b0bc797ed7f49) (by @soundofhorizon) (EDIT: fixed by 60aa205)

EDIT: merge post from @soundofhorizon by @kory33 

- [x] 範囲設置スキルの表示がクリックしても変わらない [図6](https://gyazo.com/ad5c5232af85f8a5cb86972e0b650c74) (EDIT: fixed by ef66b37)
- [x] 一括変換ページにおいて、2ページ目以降の1ページ戻るボタンがスティーブになっている [図7](https://gyazo.com/918ab8b398812266d307951ddfeaad3a) (EDIT: 多分マイクラのバグ)
- [x] Flyの表示で「毎分50」の空白の取り方が何故か異なっている [図8](https://gyazo.com/62599f9802d572f07487b9b7b9fb4063) (EDIT: fixed by #244)
- [x] 「範囲設置スキル設定画面」が開けない
- [x] 「不可壊」の文字が残っている [図9](https://gyazo.com/98f0c03c1a41dbad6a8795a90548e7b7) (EDIT: fixed by b545ef50)
- [x] 採掘速度上昇の効果がブロックを掘っても反映されない (EDIT: 整地量増加とともにfix済み)

**Comment by soundofhorizon** [comment]
- [ ] 範囲設置スキルの表示がクリックしても変わらない [図6](https://gyazo.com/ad5c5232af85f8a5cb86972e0b650c74)
- [ ] 一括変換ページにおいて、2ページ目以降の1ページ戻るボタンがスティーブになっている [図7](https://gyazo.com/918ab8b398812266d307951ddfeaad3a)
- [ ] Flyの表示で「毎分50」の空白の取り方が何故か異なっている [図8](https://gyazo.com/62599f9802d572f07487b9b7b9fb4063)
- [ ] 「範囲設置スキル設定画面」が開けない
- [ ] 「不可壊」の文字が残っている [図9](https://gyazo.com/98f0c03c1a41dbad6a8795a90548e7b7)
- [ ] 採掘速度上昇の効果がブロックを掘っても反映されない

**Comment by kory33** [comment]
All issues fixed.
