### ISSUE TITLE
デバッグ鯖バグカバレッジ #2

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#250]
## 修正済み

- [x] Y5のハーフが整地スキルで剥がれる (37c07b9, b885e59)
- [x] 遠距離系の整地スキルが壊れている。[図8](https://gyazo.com/a06e84ca9b7aab342e4d72d13f3ec6fa) (08cbbbc)
- [x] 右に棒メニュー、左(オフハンド)にシャベルを持った状態で棒メニューを開こうとするとシャベルで草ブロックを変更してしまう。本番環境では起こらないので恐らくバグ (原文ママ) (partial fix: 08171c80, complete fix: 87aa260)
- [x] 採掘速度上昇量の内訳が斜線文字になっている。 [図7](https://gyazo.com/0ad26246bea698f3ccddeebbd8a52ade) (4780efe)
- [x] サブホームポイントxを設定すると、勝手にサブホームポイント(x-1)と命名されている。 [図6](https://gyazo.com/bd97ed157efb61f0a346900c3d45f13f) (e14ccae)
- [x] メインワールドをサブホームに設定したとき、ワールド名がworld_2になっている。 (9cedd6f)
- [x] subhomeのコマンドが使えない (24c0a89)
- [x] [図1](https://i.gyazo.com/f5c0ff207b6904fb28e139aa7c0f48d0)
(https://gyazo.com/49e5b88a468092d6207843171a4b55e4) (d4aa53d)
- [x] 鉱石交換で端数が生じるとき鉱石に応じた鉱石券 + 入れた鉱石が(入れた数)帰ってくる (eba923e)
- [x] ランダムテレポートが機能していない (外部問題)
- [x] 実績ポイントの処理で矛盾が生じている [図2] (d4aa53de)
- [x] 投票ptから実績ptの変換で実績ptが加算されてない (d4aa53de)
- [x] 最小範囲を超えた設定値が表示される [図3](https://gyazo.com/508548837df777646f8aa36a2fa00ed3) (91c67f81)
- [x] ガチャ記名の表記揺れ: Minestack/整地報酬ガチャ券から = 先頭大文字・ガチャ景品交換システムから = 小文字 (4f265d7e)
- [x] 範囲設置スキルの設定画面で、「下の空洞を埋める機能」と「MineStack優先」のON/OFFが壊れている [図4](https://gyazo.com/05ed31146eb9dba33dbe819e8459219c) (EDIT: fixed by 05c25d4)

## wontfix

- [x] ブロック一括クラフトの1ページ目→2ページ目のテクスチャが剥がれている
- [x] 範囲設置スキルの範囲設定ボタンのテクスチャが剥がれている
- [x] 範囲設置スキル設定に入るボタンのテクスチャが剥がれている
- [x] 建築系マインスタック2ページめから3ページめに遷移するボタンのテクスチャが剥がれている

(たまにテクスチャが読み込まれなくなるマイクラの謎挙動による)

- [x] サーバー選択画面のGUIにて、ツールの情報が表示されている (will be resolved in #259)
- [x] RegionGUIが機能していない(`/land`がデバッグ鯖にない)
- [x] 横向きの柱状のクォーツブロックを整地スキルで壊すとバグブロックになる [図5](https://gyazo.com/813f5420041a31c41602ad76f0dd0f8e) (will be resolved in #262)

**Comment by soundofhorizon** [comment]
- [ ] subhomeのコマンドが使えない

**Comment by soundofhorizon** [comment]
- [ ] 遠距離系の整地スキルが壊れている。[図8](https://gyazo.com/a06e84ca9b7aab342e4d72d13f3ec6fa)
