### ISSUE TITLE
非ゼロのメタデータを持つブロックを整地スキルで壊すとそのままドロップする

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#262]
[図](https://gyazo.com/813f5420041a31c41602ad76f0dd0f8e)

from @soundofhorizon

**Comment by kory33** [comment]
this reproduces in both master(1.1.1) and in current develop.

**Comment by blackbracken** [comment]
これスキルの焼き直しによって修正されるべきなので1.1.3でやりましょう

**Comment by soundofhorizon** [comment]
バグブロックになるブロックの種類の追記です。
・プルファのハーフブロック

**Comment by KisaragiEffective** [comment]
ノート: 何らか手違いでメタデータが異常になっている可能性あり (詳細は検証待ち)

**Comment by soundofhorizon** [comment]
現在、未だこのバグは発生している。建築物などを壊す際に大量にバグブロックがでる。

**Comment by kory33** [comment]
relevant part: https://github.com/GiganticMinecraft/SeichiAssist/blob/b68b6966c57dd2f34f369932d4df4f78306d550d/src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala#L233

**Comment by soundofhorizon** [comment]
これ未だに治ってないです。:thinking:

**Comment by rito528** [comment]
これ今どうなってますか？

**Comment by Lucky3028** [comment]
全然残ってます

**Comment by rito528** [comment]
そんな....

**Comment by rsoba** [comment]
こちらは#1938, #2209 でおそらく修正済です

**Comment by rito528** [comment]
@rsoba 
ありがとうございます！
