### ISSUE TITLE
特定のブロックにおいて、アサルトアーマーで破壊してもminestackに入らない

### ISSUE THREAD

**Issue by soundofhorizon** [GiganticMinecraft/SeichiAssist#264]
例：
・骨ブロック(上側が白いものだとダメ。黒っぽくなっているものは入る。)
・プルファの階段ブロック(向き依存がある) [図1](https://gyazo.com/56029d7ed968177e9ccb2ed7a6605f59)

**Comment by kory33** [comment]
該当コードがかなり書き換わったのでsolvedとします
