### ISSUE TITLE
遠距離スキル発動時に出るファイヤーチャージが着弾した際、着弾周辺に炎が出る時がある

### ISSUE THREAD

**Issue by soundofhorizon** [GiganticMinecraft/SeichiAssist#265]
ブロックが出っ張ってるところにスキルを当てると炎が出る。

**Comment by soundofhorizon** [comment]
どうやら、エクスプロージョンをエフェクトにセットしている状態で、ツールの耐久が現在選択しているスキルの発動に足りなかったときに、ファイヤーチャージが着弾したところに炎のみが残る模様

**Comment by kory33** [comment]
情報ありがとうございます。治します。
