### ISSUE TITLE
ビルドプロセスの透明化

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#266]
Spigotに依存しない限り(そして今はしていないので)、外部jarを一切入れずにビルドを走らせることができる。

## Why
 - 開発環境導入時に、ビルドするだけなら外部プラグインの導入が要らなくなる
 - **Pull Request毎にビルドとテストを走らせられるようになる**

## TODO
 - 内製jarの扱いをどうにかする
 - MavenにあるアーティファクトはGradleに依存を追加する
 - そうでないアーティファクトは`pluginDependencies`フォルダにプラグインの`.jar`を入れ、コミットしてリポジトリに含める
   - 依存アーティファクトのライセンス表記を含める
 - WorldBorderに限っては著作者に連絡するのが厳しそうかつNo Licenseであったので不透明なビルドプロセスを持つ別プラグインに機能を分離してSeichiAssistからの依存を消す
 - ビルド時に`scp`で`.jar`を持ってこないようにする
 - PRのビルドを有効化しcredentialを渡さないようにする
 - PRのマージ必要条件にビルドとテストの可否を含める

**Comment by KisaragiEffective** [comment]
念の為、ルートのLICENSEにも各プラグインのライセンスへのリンクを含めたほうがいいと思います

**Comment by kory33** [comment]
ライセンスへのリンクというよりLicense Noticeをコピーすると良さそうみたいに思っていました（こういうの`/LICENSE`に入れるのが慣習なんでしょうか　何もわかりません）

**Comment by KisaragiEffective** [comment]
Discordより要約:
```
SeasonalEventsをmaven様式の依存性を通じて参照できればよりオープンになる
```

**Comment by KisaragiEffective** [comment]
「Maven様式の依存性」というが、実際に晴れポジとりサーバーを自前で建てる必要はなくて、GitHubにバイナリブロブを放り込んでもちゃんとパスさえ方式に従っていれば認識する
例: [KisaragiEffective/maven](https://github.com/KisaragiEffective/maven)

**Comment by kory33** [comment]
jitpack.ioでよさそうです
