### ISSUE TITLE
configの整地レベル上昇時に表示される文章をコード側に移す

### ISSUE THREAD

**Issue by soundofhorizon** [GiganticMinecraft/SeichiAssist#294]

**Comment by unchama** [comment]
補足です。
現状jar単体のリリースは完全に自動化が完了しています。(各ブランチへのマージが行われると、develop→デバッグ環境、master→本番環境へjarが自動リリースされる)
ただし、config.ymlはサーバ毎に固有の値に書き換える必要のある項目がある関係で、自動リリースを実現出来ません。
逆に言えば、サーバ毎に固有設定が必要な項目(servernumとDB接続情報)以外は全てコード側に定義してしまった方が良い、ということになります。

**Comment by soundofhorizon** [comment]
’獲得できる経験値量’という文章を全て’獲得できるマナ’に変更する
