### ISSUE TITLE
特定のブロックにおいて、建築スキルの範囲設置スキルが使えない問題を修正する。

### ISSUE THREAD

**Issue by soundofhorizon** [GiganticMinecraft/SeichiAssist#318]
例えば

・石炭鉱石

これらについて、確実に設置する個数を上回る数を所持している状態でも、「アイテムが不足しています」と表示され、使うことができない。

**Comment by karayuumac** [comment]
deb鯖、第一整地で検証しましたが、再現できませんでした。

**Comment by KisaragiEffective** [comment]
同じく再現できず。
Mark as if resolved
