### ISSUE TITLE
Gachaコマンドの表示・入力に関する不具合

### ISSUE THREAD

**Issue by karayuumac** [GiganticMinecraft/SeichiAssist#34]
/gacha helpで表示されるコマンド使用方法一覧における/gacha addmsは以下のようになっている
https://github.com/GiganticMinecraft/SeichiAssist/blob/8c5b9b4ea31a047f3f3de4f161f8b90088c0d7ec/src/com/github/unchama/seichiassist/commands/gachaCommand.java#L57-L58

一方でコードを見てみると、違った説明が記載されており、引数チェックも誤っている。
https://github.com/GiganticMinecraft/SeichiAssist/blob/8c5b9b4ea31a047f3f3de4f161f8b90088c0d7ec/src/com/github/unchama/seichiassist/commands/gachaCommand.java#L327-L337

**Comment by kory33** [comment]
closed by #41 and 69058ee.
