### ISSUE TITLE
ドラゲナイタイムの名称・機能変更

### ISSUE THREAD

**Issue by karayuumac** [GiganticMinecraft/SeichiAssist#342]
- [ ] 「ドラゲナイタイム」→「ギガンティックフィーバー」に名称変更
- [ ] 現在の採掘速度上昇効果付与をやめて、敵がわかないという効果に変更
- [ ] 時間を20時から22時に拡大(時間管理は今まではサーバ側でやっていたので、引き続きサーバ側でやってもいいし、プラグイン側で制御するもよし)
- [ ] 開始時に、「フィーバー！この時間MOBたちは踊りに出かけてるぞ！今が整地時だ！」と表示する

**Comment by Lucky3028** [comment]
実装はされていたのでclose
