### ISSUE TITLE
アサルトスキルとエクスプロージョンエフェクトが重い

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#347]
接続人数20人程度でTPSが半減するレベルで重たい(かなり致命的)。以前は50人程度いてもTPSは19前後をキープしていた。
timings取るとAssultTaskとExplosionTaskの時間消費が激しい。故に重さは接続人数ではなく該当スキルの使用人数に依ると考えられる。
ScalaIze時にロジック変更が入ったという噂……

**Comment by KisaragiEffective** [comment]
🤔

**Comment by kory33** [comment]
どちらかというと #353 より 1cc86fbb の方がパフォーマンスに影響が大きかったです。

最も大きな原因として、マインスタックのアイテム格納処理は思っているほど一瞬ではない（格納可能アイテムのリスト全探索してるので当たり前）のに、「ブロックから取れるアイテムを算出してマインスタックに入れるのを試みる」という処理を直方体の範囲のブロックすべてに対して行っていた点が挙げられます。

この処理のうち、アイテムの算出まではある程度仕方ないのですが、マインスタックに入れる処理と統計をインクリメントする処理に関しては別スレッドで行ってもよいものですから、これらを非同期スレッドに飛ばすことでパフォーマンスが大幅に改善しました。

さらなるパフォーマンスの改善点としては、 `dropItemOnTool`の計算に必要な情報だけ先に破壊対象のブロックから抜いてしまって具体的な計算を別スレッドでやる、というのが考えられます（後でやるかもしれません）。

ロジック変更を入れたところはあんまり関係なかったです…以前さほど問題ではなかったというのは少し不思議です。
