### ISSUE TITLE
マインスタック内の一部アイテムの消失

### ISSUE THREAD

**Issue by ruku-re-tia2017** [GiganticMinecraft/SeichiAssist#350]
オークのハーフとそれ以外の木の種類の木材とそのハーフもMineStackから消えている
新たに入れた際も鯖を移動すると消える
アプデ後～ロルバ前に鯖へ接続した垢にのみ起こる(？)

追記：羊毛のブロックも各種消えてました。

アプデ、ロルバ前の日にログインしてなかったアカウントは消失などは
してない方がいます。

**Comment by kory33** [comment]
fixed by 7720088 and 88cf02e.
