### ISSUE TITLE
運営からのガチャ券を受け取る際のクールタイムの短縮

### ISSUE THREAD

**Issue by soundofhorizon** [GiganticMinecraft/SeichiAssist#380]
https://red.minecraftserver.jp/issues/7255

**Comment by kory33** [comment]
今まではアイテム付与が(1スタックずつではなく)1アイテムずつ行われていたので(クライアント側)負荷軽減の為のクールタイムであったと推測しています。

いずれにせよクールタイムは3から5秒程度で十分なのではないかと予想しています。

**Comment by kory33** [comment]
1sに変更済みです
