### ISSUE TITLE
凝固系スキルの発動範囲がずれている

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#427]
凝固できる範囲のY座標が、従来の仕様よりずれる。
ダイヤモンド・ダスト：
従来は、自分自身を中心に凝固できていたはず。
現在は、自分自身から上方向に凝固できるようになっている。
ホワイトブレス：
下範囲1マスしか凍らなくなっている。

報告者：kagely、minihina
報告日：2020/1/24、2/8

**Comment by kory33** [comment]
relevant part:
https://github.com/GiganticMinecraft/SeichiAssist/blob/98b9687aa346a79a7cf097e01c1a20ea0df9a2d8/src/main/scala/com/github/unchama/seichiassist/data/BreakArea.scala#L27

**Comment by kory33** [comment]
fixed by 87f3ebccb16bc4e8d0b44c018c9d87b599cce0e5.
