### ISSUE TITLE
グリッド式保護の処理の順序が前後するせいでうまく確保できない

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#434]
> ヴァルハラサーバーのみで起こる現象なのですが、グリッド式保護設定メニューでユニットを増減するとチャットログ及び実際の挙動におけるselection clearedとpos1 setとpos2 setの順番が不定になり、正しく領域を設定することができません。整地2です
> 4でも同じように順番がおかしくなりました。
> スポーンワールドも同じようにおかしいです。

(ママ)

[permalink 1](https://discordapp.com/channels/237758724121427969/573131925158494220/676456630971269141) [permalink 2](https://discordapp.com/channels/237758724121427969/573131925158494220/676458270763909120)

付記: レースコンディション・・・？

**Comment by KisaragiEffective** [comment]
要検証:
- アルカディア、エデンでも起きるか？ (おそらくはい)
- どの時間帯でも起きるか？ (おそらくはい)
- 誰がやっても起きるか？ (おそらくはい)
- 座標で起きなかったりするか？ (おそらくいいえ)

**Comment by kory33** [comment]
グリッド式保護、まだメニュー化されてないんで挙動変わってないはずなんですけど、これ以前から起きていたんでしょうか

**Comment by KisaragiEffective** [comment]
unverifiable on current release
