### ISSUE TITLE
eulaがtrueになってなかったときにcomposeサービス全部落とす

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#450]
可能なのかわからない　spigot_aが死んだら全部終了するみたいなロジックがcomposeに書けなかったらオワリ

**Comment by kory33** [comment]
https://stackoverflow.com/questions/33799885/how-to-stop-all-containers-when-one-container-stops-with-docker-compose

**Comment by hsjoihs** [comment]
「eula=false を eula=trueに書き換えてください。」の後に./prepare-docker.shを再実行すべき旨をREADMEに書いとくと良さそうです
