### ISSUE TITLE
整地スキルにより手に入れたブロックがマインスタックに収容されていない

### ISSUE THREAD

**Issue by soundofhorizon** [GiganticMinecraft/SeichiAssist#459]
https://youtu.be/XzT1KXOuheM

reported by kazuta, kei

**Comment by soundofhorizon** [comment]
本番環境で起きているバグらしいです

**Comment by KisaragiEffective** [comment]
Can Reproduce.

**Comment by soundofhorizon** [comment]
関係しそうでしたのでここに連ねておきます

自動マインスタックをオフにした状態で整地をした際、正しくアイテムをドロップする処理ができていない

との報告がありました。

ツルハシ以外を用いてアサルトスキルを使用した場合は自動マインスタックをオフにすると消滅するらしいです。

**Comment by kory33** [comment]
@soundofhorizon moved to #460

**Comment by kory33** [comment]
マイクラの仕様として、シャベルで石や鉱石を掘ったりしても何も出ないというのがある
なのでエンチャントが同じダイヤのシャベル＋ツルハシで破壊試行をしてmaxを取る必要がある

**Comment by KisaragiEffective** [comment]
もしかして: こないだgetDropsに変えたせい

**Comment by kory33** [comment]
fixed: 929e56c0

**Comment by kory33** [comment]
嘘　なんかおかしい

**Comment by KisaragiEffective** [comment]
```scala
def calculateDrops(e: BlockBreakEvent) {
  // ...
  e.setDrops(new BlockBreakEvent(e.itemstack.asIfShovel).getDrops ++ new BlockBreakEvent(e.itemstack.asIfPickaxe) ++ new BlockBreakEvent(e.itemstack.asIfAxe) ++ new BlockBreakEvent(e.itemstack.asIfSword))
}
```
:thinking:

**Comment by kory33** [comment]
と思うじゃないですか？ダメでした　Bukkitがダメ

**Comment by KisaragiEffective** [comment]
？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by kory33** [comment]
fixed: a1c8b13f
