### ISSUE TITLE
ガチャ券の当たり、大当たり等の通知を一つに纏める

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#472]
ガチャを回すときの通知を

「64回ガチャを回しました。
おめでとう当たり!
おめでとう当たり!
おめでとう当たり!
おめでとう!!大当たり」
から
「64回ガチャを回しました。
当たりが5個、大当たりが5個出ました」
などに変える。

https://red.minecraftserver.jp/issues/7421

**Comment by KisaragiEffective** [comment]
Implemented in #502
