### ISSUE TITLE
遠距離スキルの矢をぬっ殺す

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#475]
確かPlayerにそういう感じのメソッドがあったようなきがする :thinking:

**Comment by kory33** [comment]
これはなに

**Comment by KisaragiEffective** [comment]
「現在遠距離スキルは矢を発射しているが・・・プラグインでブロックを読み込んで破壊するようにする」(ソース: 春アプデ) という趣旨のissueです :thinking:
