### ISSUE TITLE
整地スキルエフェクトを購入できない

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#479]
「整地スキルエフェクトを購入しようとして、使えるエフェクトポイントを十分所有しているのに購入できない」

所有ポイント128
すべてのエフェクトで同様の状況が発生する

報告者：wolf_kemono
報告日時：20/3/26 13:42

https://red.minecraftserver.jp/issues/7602

**Comment by kory33** [comment]
#522 で実装が差し替えられました
