### ISSUE TITLE
チェストが破壊できない

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#490]
#487 以降チェストが整地スキル切ってても破壊できないらしい

**Comment by kory33** [comment]
hotfixブランチで直します

**Comment by kory33** [comment]
再現しない

**Comment by unchama** [comment]
運営宛に報告いただいた内容をこちらにも。

アルカディア、エデン、ヴァルハラ、建築サーバーで、メインワールドに設置した、もしくは設置してあるチェストを素手、またはツールを使用して破壊しようとすると
「スキルでのチェスト破壊は整地ワールドでのみ有効です」(パッシブスキル「チェスト破壊スキル切り替え」発動中)
「スキルでのチェスト破壊は無効化されています」(パッシブスキル「チェスト破壊スキル切り替え」未発動)
と赤色でチャットに表示されチェストの破壊が不能となっております。
全サーバーの整地ワールド(第1~4, ネザー, エンド)では破壊できるようです。
