### ISSUE TITLE
ガチャ券を配布した場合に、配布日時以降に初めて参加した人にガチャ券を与えない

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#499]
「運営からのガチャ券を受け取る」ボタンで受け取ることのできるガチャ券に関するもの。

https://red.minecraftserver.jp/issues/7650

**Comment by yuuki1293** [comment]
現在そのような仕様になっています

**Comment by rito528** [comment]
情報ありがとうございます！
