### ISSUE TITLE
言語切り替えインターフェースの実装

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#503]
言語設定により、木の棒メニューなどの表示言語に日本語以外を選択できるようにするインターフェースを構築する。

**Comment by soundofhorizon** [comment]
https://www.seichi.network/for-visitors
この機能を実装した場合、ここのページはどのような意味として解釈すればいいのでしょうか

**Comment by unchama** [comment]
このページが要らなくなるくらい英語が充実すると良きですね。

**Comment by rito528** [comment]
現状のアクティブプレイヤーの中で外国人プレイヤーというのはとても少人数で、労力に見合わないのでクローズ。
