### ISSUE TITLE
インベントリ共有機能失敗時のエラーメッセージに含まれるカラーコードが展開されていない

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#504]
https://gyazo.com/d9c2c662ff2e06eec3aa5e50f58b1536
アルカディア メインワールドで4/29 21:30頃に発生しました。
インベントリ共有機能失敗時のエラーメッセージの文頭に${RED}という文字列が含まれています。

報告者：Re_sobaaa
報告日時：4/29 21:36
https://red.minecraftserver.jp/issues/7765

**Comment by KisaragiEffective** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/c9c9cb6600f4f6341d8700d3fc801eec6a6d696c/src/main/scala/com/github/unchama/seichiassist/database/manipulators/PlayerDataManipulator.scala#L304
