### ISSUE TITLE
棒メニューの建築量が指数表記になっている?

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#516]
1.0E7みたいな。
https://discordapp.com/channels/237758724121427969/237758724121427969/717397917857611786

**Comment by KisaragiEffective** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/6fa1eed2e1bf754c6d5062e9f0a035a64ccd98e1/src/main/scala/com/github/unchama/buildassist/menu/BuildMainMenu.scala#L73

**Comment by KisaragiEffective** [comment]
https://docs.oracle.com/javase/jp/8/docs/api/java/lang/Double.html#toString-double-
> 10<sup>7</sup>以上の場合は、浮動小数点表示形式で表現される。

**Comment by soundofhorizon** [comment]
これ、DBで直接build_countの値を10000000にしたらこうなりました
