### ISSUE TITLE
メビウスの命名において、全角スペースをスペースとして認識していない

### ISSUE THREAD

**Issue by soundofhorizon** [GiganticMinecraft/SeichiAssist#518]
https://github.com/GiganticMinecraft/SeichiAssist/blob/911199b54d5d7ed20be3a7af9900d93a96a95721/src/main/scala/com/github/unchama/seichiassist/commands/MebiusCommand.scala#L79

**Comment by kory33** [comment]
@KisaragiEffective @soundofhorizon 
そういえばこれどういうissueでしたっけ？

**Comment by kory33** [comment]
問題意識がクリアでないため一旦closeします
