### ISSUE TITLE
整地量計算にMinecraftの統計を使用しない

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#557]
現行の実装では、スキル等でのブロック破壊時にはMinecraftの統計をインクリメントしている。
そして、 `PlayerData` 内に統計情報のスナップショットを一時保管し、
1分ごとにバッチ処理として差分から整地量を算出するという仕組みになっている。

しかし先程、どうやら石を21億ブロック掘って統計がオーバーフローしてしまい、統計インクリメントが `IllegalArgumentException` を吐くようになってしまった人がいるらしい。

破壊量的な都合で、そもそも整地鯖ではMinecraftの統計をインクリメントするべきではないと考える。

related: #542.

当issueが解消されるまでは上記と同等の挙動を踏んでしまう人が現れる可能性があるため、もしそのようなことが起こった場合は **そのプレーヤーがサーバーに入っていない状態で** ワールドデータのjsonを直接書き換えるという対応が必要になる。
もしプレーヤーがサーバーに入っている状態でこの操作が行われても解消されない場合があり、最悪整地量が21億ほど誤って加算される可能性がある。

**Comment by KisaragiEffective** [comment]
ぶっ壊れてる…という感想はさておき。統計の値が`Integer.MAX_VALUE`である場合は統計のインクリメントをスキップすれば良いのでは？

**Comment by kory33** [comment]
整地量計算に統計を経由しないように書き換えたうえで統計をオーバーフローさせないように頑張るということですか？

**Comment by KisaragiEffective** [comment]
```java
if (とうけい /* クラス名 */.value() < Integer.MAX_VALUE) {
  とうけい.increment();
}
```

**Comment by kory33** [comment]
単純にこれをやると整地量が加算されなくなります(整地量計算は統計の差分を見ている)。

結局オーバーフローを防止するためには `onBlockBreak` でも統計を増やさないために
イベントをキャンセルする必要があります。そこまで塞いでしまうならばいっそ全面的に統計の増加を阻止し、
整地量と言う単一の統計にまとめてしまったほうが良さそうです。

**Comment by kory33** [comment]
> stouma915Today at 5:30 PM
> #plugin開発-notification これって、算出が終わったら統計をリセットすればよくないですか？(間違ってたらすみません)

暫定的にこのfixを入れるべきっぽい
