### ISSUE TITLE
ガチャを手に持って"MineStackガチャテーブルに"追加する機能が動作していない

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#56]
> 今、ガチャの方の「手に持ったアイテムがマインスタックに追加される」機能、バグってるのかなんなのか不可能なんですけど…

> ガチャはもともと手に持って追加するコマンドがあるんですよ！（コードどこに書いてあるか忘れた:innocent: ）　でも正常に動いてないんです:joy: 
レベルは収納レベルのことだと思いますが私もよくわからないです…でも無視してちゃんと登録されてるなら良いのでは:thinking:

> 交換券を無理やり突っ込もうとしたんですけどうまく格納されなくて…

(#plugin開発 で kawakuroさんによる)

**Comment by rito528** [comment]
仕様が変わってガチャシステムに依存するようになったのでクローズ
