### ISSUE TITLE
ガチャ景品が意図せずドロップしている

### ISSUE THREAD

**Issue by soundofhorizon** [GiganticMinecraft/SeichiAssist#564]
以前の変更( #436 )において、ガチャドロップは条件を満たした際直接マインスタックに入るようにしたはずだが、現時点のmasterではドロップしてしまっている

**Comment by KisaragiEffective** [comment]
変更履歴: (上が新しく、下が古い)
|ハッシュ|PR/Issue|備考|
|:----:|:-:|:-:|
|...|#564||
|58aa42cd4ecd9df9ec4ed53fbd6e2f8964d0e068|||
|a2fb9e089637ce1fc228205150fbe7f86f18a909|||
|4fb050024961baa4754a9f3db72465e20bf26b78|||
|5bfbc6570744656ebfed90bfbcfff7eca233f1ff|||
|1968db5df7188ce3a558a58bdd0ac02a1787cfbd|||
|1a941c3b7c5b3a5657aecb444bcc5ea37aa75338|||
|8fa25e6d0e86798055caa4fdc4bce22d22de8702|||
|9f9d13eef0afdc661614c20b22fa8a83344e0ea9|||
|8cdf53a6ed545652b2281d573be39e3470f67273|||
|81bebeb4f262cf71112dbc1a0cb81b4f50f16382|||
|b377936130c4f9fb268c86e8f9529a59b7e3d27f|||
|fb233ec1bbddf71fcbee542d044d1c6f687fbe75|||
|ac260e849ec5720f9ba50aab838d542f0d5ba5ac|||
|...|#534||
|d4dff364f6558ecf8a8434f53fd9dfc90bcb106f|||
|...|#502||
|e790bbd64d744290d951e2444517f999d82b9c97|||
|dc19229d4e54a0b0e6b0d90c969dd2a716b98e68|||
|5e92787d2eb25a1baf05bfb2fc00af4496295f1d|||
|2899410cb0eab22f5a3cfadd532b36adad5788b0|||
|2196223bd5ffe29119cbc0916f7f7395a8108fff|||
|||
|...|#491|1.2.14-hotfix3|
|bef54166b06b1cd2bd7d312ed13c492c3cdaeb70|||
|357d271c3123a55442e55309f4fe04676d2a9df7|||
|||
|...|#487|1.2.13|
|539d901f54f69cc9fee114fcfdc1f560bd68baf1|||
|472c5a9712f8bf7812d714a050d703ec85d58edf|||
|3ebb516a9378b1544e09258d9a6c5b5880486495|||
|||
|...|#463|1.2.12|
|f957d4531fba5b8b53d812f2058f0e32ae6a8af7|...||
|...|#445||
|9f31b9f156cb8341ff92692680c7d4a862dffcbc|...||
|4b852e25cf1bcd097c79f2c3d0f6f6f36a6e1c65|...||
|fdb82e3134604d38c9c3e700799663cd2e0c9a0b|#436||

**Comment by Lucky3028** [comment]
第12回アイデア会議にて承認された
https://redmine.seichi.click/issues/9675

**Comment by rito528** [comment]
#1502 で直ったはずです
