### ISSUE TITLE
コーラスフルーツ→焼いたコーラスフルーツ → プルプァブロックの変換列を一括クラフトに追加する

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/SeichiAssist#605]
due to https://red.minecraftserver.jp/issues/7423.

**Comment by Lucky3028** [comment]
これやってみようと思ったんですけど、レートはどんな感じにすれば良いんです？

**Comment by kory33** [comment]
レートあんまり決まってなさそう(精錬レシピは他の精錬レシピ同様に燃料を消費して、クラフトレシピは無損失のレート、で良さそう)です

**Comment by Lucky3028** [comment]
了解ですー
