### ISSUE TITLE
金床にほとんどのアイテムを置いても「MEBIUSへの命名は」と表示されキャンセルされる

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#654]
ポーションとエンチャントの本ではこの現象は発生しないことを確認した。

報告日：2020/8/23 11:59
報告者：ilohas0096
参照：https://red.minecraftserver.jp/issues/8328

**Comment by Megumiso** [comment]
https://discordapp.com/channels/237758724121427969/237758724121427969/751273318187008131

workaround: 数字キーでアイテム移動。
というかカーソルと数字キーを使った移動方法で挙動が異なるのはまた不具合では(名推理)

**Comment by KisaragiEffective** [comment]
マウスで移動しない場合は`getCursor(): ItemStack | Null`が`null`となり、結果うまく動かないのでは？

**Comment by Lucky3028** [comment]
InventoryClickEventで、getActionがInventoryAction.HOTBAR_SWAPもしくはInventoryAction.HOTBAR_MOVE_AND_READDと等しければ数字キーでアイテム移動っぽいです
