### ISSUE TITLE
保護の範囲のy座標が色々おかしい

### ISSUE THREAD

**Issue by kaeru82433413** [GiganticMinecraft/SeichiAssist#664]
1.
s1,s2で、保護の範囲を`斧で選択`した場合や`//pos1,//pos2コマンドを使って指定`した場合に、yの範囲が0から256の257ブロックになる。(グリッド式保護設定メニューからだと0-255で正常。)

2.
面積1ブロック=㎡　225㎡=1ユニット　体積1ブロック=㎥
整地2,整地4の保護の最大サイズがそれぞれ14688000㎥(=256ユニット\*255),293760000㎥(=5120ユニット\*255)になっている。(つまり高さが256ではなく255になっている。)

上の二つの不具合から、例えばs1整地4だと293760000/225/257=5080.15…となり、5080ユニットしか保護が取れないことになる

EDIT by @kory33: markupを直しました

**Comment by kory33** [comment]
報告ありがとうございます！

1. SeichiAssistの問題ではなさそう
2. 設定の問題っぽいので別箇所にフォワードします
