### ISSUE TITLE
土・草ブロックの整地量カウントが正常に行われていない

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#665]
土・草ブロックのみ整地量のカウントが半分になっている

報告者：kouta6230
報告日時：20/9/1 01:30
参照：https://red.minecraftserver.jp/issues/8355

私（Lucky3028）及びTAMA_EXPさんがそれぞれs2とs3の第1整地で確認した。

**Comment by karayuumac** [comment]
統計を見つつ検証してみると、

- シルクタッチで草ブロックを掘ったとしても土ブロックを掘ったものとしてカウントされる
- シルクタッチなしで草ブロックを掘っても土ブロットを掘ったものとしてカウントされる

なのでこれが正しければ、
```scala
//DIRTとGRASSは二重カウントされているので半分に
      case Material.DIRT => 0.5
      case Material.GRASS => 0.5
```
の重み分けは不要のように感じる。

More information needed
