### ISSUE TITLE
期限切れ保護削除コマンド(/rmp)で対象保護を全削除出来る様にしたい

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#667]
前までは削除日数を負の値にすることで擬似的に実現できていた機能。Scala-ize時に入力検査が強化？されて使用不可となった(それはそう)。ワールド手動再生成時にあるとラクになるので嬉しい。

**Comment by KisaragiEffective** [comment]
Note
https://github.com/GiganticMinecraft/SeichiAssist/blob/develop/src/main/scala/com/github/unchama/seichiassist/commands/RmpCommand.scala

**Comment by KisaragiEffective** [comment]
というか「削除日数を負の数にする」とはどういうことでしょうか…

**Comment by Lucky3028** [comment]
再生成を行うのに、RegenWorldを使わずに物理的にワールドデータをいじるなり、Multiverseのregen機能で生成するなりでやったときには、保護情報が消えないわけです。なので、保護情報が記録されてるファイルをいじるのも大変なので、rmpコマンドで-1（つまり負の数）を指定することで、存在する保護を全部消せるんじゃないかというお話です。

**Comment by KisaragiEffective** [comment]
なるほど、ただそれだと文脈が不明確なような…？

**Comment by unchama** [comment]
-1にすると判定日付が未来日時になり、「最終ログイン日時が未来日時より前のプレイヤーをOnwerとする保護を全て削除する」というロジックに化け、これが実質全削除と同じ挙動だっただけの話で、実際のところは除外region以外全部消すというロジックがあればOKです。
