### ISSUE TITLE
二つ名組み合わせメニューで次ページに行かない。

### ISSUE THREAD

**Issue by Megumiso** [GiganticMinecraft/SeichiAssist#668]
再現方法:
1. 二つ名組合せメニューで「中パーツ」を表示させる。
2. 次ページを選択する。

想定された動作:
次のページが表示される。

実際の動作:
永遠に一ページ目が表示される。
https://gyazo.com/cbf34e6a7fc8dd80dc630bb77e312dc7

**Comment by unchama** [comment]
二つ名一覧のパーツ表示内容は、中パーツの場合、`middlePartIndex`に格納された値を見て決定している模様。
https://github.com/GiganticMinecraft/SeichiAssist/blob/2b580251064e643632a29d10745b392aab24d184/src/main/scala/com/github/unchama/seichiassist/data/MenuInventoryData.java#L534

MHF_ArrowRight(次ページ)を押された時にはmiddlePartIndexの値をズラさないと延々と同じところが表示される気がするが、ズラしてる記述が特に見当たらない。ズラす処理を足せば直りそう？
https://github.com/GiganticMinecraft/SeichiAssist/blob/2b580251064e643632a29d10745b392aab24d184/src/main/scala/com/github/unchama/seichiassist/listener/invlistener/OnClickTitleMenu.scala#L190

あと、MHF_ArrowLeft(前ページ)を押された時の処理はそもそも無さそうなので足さないといけないかも。

上記は中パーツの場合だが、前パーツと後パーツも同様と思われる。格納されているHashMapの名前とメソッド名が異なるので注意されたし。
