### ISSUE TITLE
homeを外部プラグインからSeichiAssistにマイグレーションして強化する

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#691]
> -home(外部プラグイン)を淘汰してsunhome(SeichiAssist)をhomeに昇格

― by @unchama, https://discordapp.com/channels/237758724121427969/732894567782809660/762300615304544276

**Comment by unchama** [comment]
home(外部プラグイン)を淘汰する際、データの保全は考慮しなくてかまいません。
