### ISSUE TITLE
整地スキルのON・OFFの表示及び実際の挙動がずれる

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#702]
アサルトスキルoffごとにずれている？
放置等で「アサルトスキルがoffになりました」とでると破壊off＋凝固onか破壊on＋凝固offとなるので
次の「アサルトスキルがoffになりました」の表記を出すまで片方しか発動しなかったです

[参考画像](https://cdn.discordapp.com/attachments/324180473649692682/765157825684701204/unknown.png)

報告者：shirotubu
報告日時：2020/10/12 19:24

**Comment by lis2a** [comment]
別々になっているようなので、恐らく修正できていると踏んだ
(検証、ありがとう！)
