### ISSUE TITLE
定期実行タスクに失敗する

### ISSUE THREAD

**Issue by Megumiso** [GiganticMinecraft/SeichiAssist#707]
1分ごとに実行される定期タスクが失敗してしまい、これにより、採掘速度上昇が付与されなくなってしまう。

↓サーバーログ

> [Thu, 15. Oct 2020 19:08:22 JST INFO] 定期実行タスクの実行に失敗しました
[Thu, 15. Oct 2020 19:08:22 JST WARN] java.util.NoSuchElementException: key not found: 9bb8ea2a-36d0-4cfb-9214-5bf8abacf069
[Thu, 15. Oct 2020 19:08:22 JST WARN] at scala.collection.MapOps.default(Map.scala:246)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at scala.collection.MapOps.default$(Map.scala:245)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at scala.collection.AbstractMap.default(Map.scala:376)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at scala.collection.mutable.HashMap.apply(HashMap.scala:405)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at com.github.unchama.seichiassist.task.global.PlayerDataRecalculationRoutine$.$anonfun$apply$3(PlayerDataRecalculationRoutine.scala:37)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at com.github.unchama.seichiassist.task.global.PlayerDataRecalculationRoutine$.$anonfun$apply$3$adapted(PlayerDataRecalculationRoutine.scala:36)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at com.github.unchama.seichiassist.task.global.PlayerDataRecalculationRoutine$.$anonfun$apply$2(PlayerDataRecalculationRoutine.scala:36)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:359)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:380)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:323)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.Callback$AsyncIdempotentCallback.run(Callback.scala:130)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:89)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:89)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:89)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:136)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:125)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at com.github.unchama.concurrent.bukkit.BukkitServerThreadIOShift.$anonfun$shift$4(BukkitServerThreadIOShift.scala:47)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[Thu, 15. Oct 2020 19:08:22 JST WARN] at java.lang.Thread.run(Thread.java:748)

**Comment by KisaragiEffective** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/blob/e7b0ee2f57cf189fe946c134472db3d06df0f860/src/main/scala/com/github/unchama/seichiassist/task/global/PlayerDataRecalculationRoutine.scala#L37
で`player.uniqueid`が`SeichiAssist.playermap`にキーとして存在するかどうかを確認していないのが原因

**Comment by kory33** [comment]
これ存在しないのおかしいのでどんなケースで存在しなくなるかを知りたい感がある

**Comment by stouma915** [comment]
![image](https://user-images.githubusercontent.com/62248740/98455625-9905f100-21b6-11eb-8a7d-3b603adc8e99.png)
> (もしかしてunload requestが行われてplayerdataが存在しないままプレーヤーが存在しているわずかな時間にこれが起こっている？)
そんな感じのログがありました

**Comment by kory33** [comment]
そのログ、なんで二度もunloadしようとしてるんですかね… 🤔 

いずれにせよunload requestが行われた後のわずかな時間にplayerdataへのアクセスが走ると死ぬので、
[BungeeSemaphore](https://github.com/GiganticMinecraft/BungeeSemaphore) が解決してくれるという認識です

**Comment by kory33** [comment]
(BungeeSemaphore自体は完成してて、SeichiAssist側がredisにプレーヤーデータ保存後に適切なシグナルを送れば動きます　そこがまだ未実装)
