### ISSUE TITLE
MenuSessionでConcurrentModificationExceptionが投げられる

### ISSUE THREAD

**Issue by karayuumac** [GiganticMinecraft/SeichiAssist#709]
MenuSession.overwiteViewWithにおいて、ConcurrentModificationExceptionが飛ぶ。
2019/11にすでに修正がかけられているようだが、いまだ発生している状態。

<details>
<summary>エラーログ</summary>
<pre>
[Mon, 14. Sep 2020 22:34:49 JST INFO] BuildMainMenuを開く最中にエラーが発生しました。
[Mon, 14. Sep 2020 22:34:49 JST WARN] java.util.ConcurrentModificationException
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at java.util.ArrayList$Itr.next(ArrayList.java:859)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at scala.collection.convert.JavaCollectionWrappers$JIteratorWrapper.next(JavaCollectionWrappers.scala:39)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at scala.collection.mutable.Growable.addAll(Growable.scala:62)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at scala.collection.mutable.Growable.addAll$(Growable.scala:59)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at scala.collection.immutable.SetBuilderImpl.addAll(Set.scala:315)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at scala.collection.immutable.Set$.from(Set.scala:272)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at scala.collection.IterableOnceOps.toSet(IterableOnce.scala:1241)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at scala.collection.IterableOnceOps.toSet$(IterableOnce.scala:1241)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at scala.collection.AbstractIterable.toSet(Iterable.scala:921)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at com.github.unchama.menuinventory.MenuSession.$anonfun$overwriteViewWith$14(MenuSession.scala:79)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:359)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:370)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:89)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:89)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:89)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:378)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:323)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IOParMap$ParMapRunnable.complete(IOParMap.scala:97)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IOParMap$ParMapRunnable.$anonfun$callbackA$1(IOParMap.scala:67)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IOParMap$ParMapRunnable.$anonfun$callbackA$1$adapted(IOParMap.scala:60)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:359)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:380)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:323)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at cats.effect.internals.IOShift$Tick.run(IOShift.scala:35)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Mon, 14. Sep 2020 22:34:49 JST WARN]     at java.lang.Thread.run(Thread.java:748)
</pre>
</details>

**Comment by kory33** [comment]
[.toSet](https://github.com/GiganticMinecraft/SeichiAssist/blob/430908b9186e77f86ef67b04d5a5565b43590fe5/src/main/scala/com/github/unchama/menuinventory/MenuSession.scala#L79)のRead-Write競合っぽい…うーんどうしようこれ…

**Comment by kory33** [comment]
メインスレッドに処理を飛ばすのが最良っぽい
