### ISSUE TITLE
個人チャットのブロック機能

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#741]
ブロック機能の実装であれば、工数が掛からない順で

* 元のコマンドと一緒の文字列で、標準のコマンドよりも優先度を高くし元のコマンドを制限して、プライベートチャットを実装(工数が少なくて済む, Siro_256さんが仰っていました)
* PlayerCommandPreprocessEventでブロックされていれば弾く(実装が若干面倒, 「ブロックした」ではなく「ブロックされた」でリスト保存する必要がある)
* ブロックしているプレイヤーのIDを含むtextが入ったパケットを受け取らないように(呼ばれる回数が頻繁, 実装にひと手間必要な上ProtocolLibが必要になる, 強度は高い)

のいずれかで満たせるかと思います

（unicroakさん、2018/1/8）

参照：https://red.minecraftserver.jp/issues/2997

（SeichiAssistじゃなさそう）

**Comment by Megumiso** [comment]
もしかしたら GiganticMinecraft/SeichiAssist-ExternalLib#21 これでおまけで実装できてしまうかも

**Comment by yuuki1293** [comment]
/ch hide <player_name>
で要件を満たしてそうです
tellが貫通しないのは検証済み

**Comment by Lucky3028** [comment]
LunaChatに移行したのでそれで解決する感じですね、ありがとうございます！
