### ISSUE TITLE
飛翔体をspawnという保護の中では飛ばせないようにする

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#746]
題名通り。

参照
https://red.minecraftserver.jp/issues/7608
https://red.minecraftserver.jp/issues/8540

**Comment by Lucky3028** [comment]
本番環境だと機能していないらしい...なぜ...

**Comment by Lucky3028** [comment]
メインワールドのspawn保護の名前は「spawn-center」でした直します

**Comment by Lucky3028** [comment]
Shift+右クリックで一気に割るのも回避できないらしい

**Comment by Lucky3028** [comment]
* 保護が重なっている場合がほとんどなので、getOneRegion関数だとすり抜ける
* 耐久値が減る、手持ちのアイテム数のを阻止できていない

**Comment by kory33** [comment]
Shift+右クリックは今全然重くないはずなんですが禁止する必要ありますか？

**Comment by Lucky3028** [comment]
サーバールール的にそうですね
3条3項「プレイヤーが集中する場所で、エフェクトの出る武器やアイテムを多用しクライアントまたはサーバーに負荷をかける行為（例：弓、経験値瓶割り、花火）」

**Comment by kory33** [comment]
１スタック投げてもエンティティ高々2とかですが負荷になり得るんでしょうか…？

**Comment by Lucky3028** [comment]
All値が200超えちゃうと、どっちかというとクライアント側がガクガクっとなる場合があって、実際に処罰もしていてという感じです

**Comment by kory33** [comment]
#599 により経験値瓶投げた時のAll値寄与は極端に少なくなっているという認識があるのですが、
未だに経験値瓶での負荷が理由で処罰が発生していますか？(一体どれだけオーブ溜めたらそうなるんだという感じがします)

**Comment by Lucky3028** [comment]
最後にこの理由で処罰したのは7/14ですね
ならいいか
