### ISSUE TITLE
イベント系の処理をSeasonalEventsディレクトリ下にまとめて整理する

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#750]
せっかくなので、1周年記念のものや新年・ハロウィンのやつなんかをSeasonalEventsの方にまとめちゃおうと思うんですがどうですか？

**Comment by kory33** [comment]
いいと思います！できれば subsytem の中に入れてもらえると助かりそう (SeichiAssistと完全疎結合には多分ならないので)

**Comment by kory33** [comment]
とりあえず `unchama.seasonalevents` に移すというのでもアリ

**Comment by Lucky3028** [comment]
subsystemディレクトリの中のやつ、前にいろいろ読んではみたんですが、IOとかEffectとかさっぱりわからずじまいだったので厳しそうです。
とりあえず`unchama.seasonalevents`で...

**Comment by kory33** [comment]
`subsystem` の中でも [`rescueplayer`](https://github.com/GiganticMinecraft/SeichiAssist/tree/9704223a2771f9b94d767def2ac4d13e4650aa39/src/main/scala/com/github/unchama/seichiassist/subsystems/rescueplayer) は `IO` や `Effect` は入っていないので、アイデアを見るにはこれが最適だと思います。

Mebiusやとかが `Effect` なんかを要求しているのはコアにある(ビジネス)ロジックをBukkitやスケジューラから極限まで引き剥がしたり、テストを回すために純粋プログラミングをやるためだったりするので、無理にやる必要はないと思っています。

**Comment by kory33** [comment]
ただ、とりあえず `unchama.seasonalevents` でも大丈夫です！

**Comment by Lucky3028** [comment]
なるほど、ありがとうございます。い、いずれ試してみる形ということで...

**Comment by Lucky3028** [comment]
* n周年記念イベントで、記念のプレイヤーヘッドを配布する
* 新年イベントで。大晦日に参加した人にカスタムヘッドを配布する
* バレンタインイベントで、期間中にログインした人にオリジナルアイテムを棒メニュー経由で配布する

という処理がそれぞれあって、それぞれを各プレイヤーに配布したかどうかのフラグがDBにあります。
これって、「インベントリに直接アイテムを入れる or インベントリに空きがないなら周りにドロップする」ようにした上で、「ログインしたときにlastquitがイベント開始日より前であれば」という条件に全て置き換えれば、配布したかどうかのフラグいらなくなりません？

**Comment by kory33** [comment]
正しそうです！

**Comment by kory33** [comment]
ただ、そこのリファクタリングは別issue or PRに切り出してもよさげですね

**Comment by Lucky3028** [comment]
なるほど、なら別の時に。
