### ISSUE TITLE
スキルを使って重ねた半ブロックが破壊できる

### ISSUE THREAD

**Issue by Megumiso** [GiganticMinecraft/SeichiAssist#775]
できちゃった。

**Comment by KisaragiEffective** [comment]
Y=5の話ですか？

**Comment by Lucky3028** [comment]
そうですね、ハーフブロックの破壊キャンセルが効いてるやつです。

**Comment by KisaragiEffective** [comment]
これY=5にある石の(重なっていない)ハーフブロックが破壊できないだけで、仕様のとおりなのではという気がしてきた

**Comment by Lucky3028** [comment]
y5に設置された石ハーフブロックについてのバグ報告です。
y5に設置された石ハーフブロックは、整地鯖の設定により、外せない仕様となっていますが、
これを外す方法が見つかりましたので、報告します。

・y5の石ハーフブロックを二枚重ねにする
・なんらかの整地スキルで二枚重ねになった石ハーフブロックを破壊する

おそらく、整地スキル対象に、「二枚重ねの石ハーフブロック」が追加されてからの問題です。
y5の石ハーフブロックを外せない仕様と、競合しているのだと思います。

ref. https://red.minecraftserver.jp/issues/7519
