### ISSUE TITLE
鉄鉱石&石炭->鉄インゴットのクラフトを一部削除・追加

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#784]
4&1→4を削除し、4000&1000→4000と40000&10000→40000を追加

https://red.minecraftserver.jp/issues/8603

**Comment by kory33** [comment]
金鉱石の方は変更なしで良いんです？

**Comment by Moca3** [comment]
あー
金鉱石もでした..
ありがとうございます、変更します

**Comment by kory33** [comment]
良さそう
