### ISSUE TITLE
ドラゲナイタイムの内容追加

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#785]
現行のものに加えて、時間中のマナ使用量減少20%

https://red.minecraftserver.jp/issues/8659

**Comment by Lucky3028** [comment]
ドラゲナイタイム、コマンド自体はSeichiAssistではない別のなんかスケジュールしてコマンド打ってくれるプラグインから打っていることを思い出した

**Comment by stouma915** [comment]
~~crontabかとずっと思ってた~~

**Comment by Lucky3028** [comment]
（そうかも...よくわからない...なんか覚えてらっしゃいませんか？ ）@unchama

**Comment by unchama** [comment]
これですね……
https://github.com/GiganticMinecraft/SeichiAssist-ExternalLib/blob/main/plugins/tce/README.md

**Comment by Lucky3028** [comment]
あ！謎プラグインだ！

**Comment by stouma915** [comment]
ドラゲナイってセカ〇ワdragon nightのことですか？

**Comment by Lucky3028** [comment]
たぶんそうです、私はそう思ってました

**Comment by stouma915** [comment]
わかりました

**Comment by KisaragiEffective** [comment]
再実装しませんか？

**Comment by stouma915** [comment]
再実装しようとしてるんですけど、サブシステムにするべきですか？

**Comment by KisaragiEffective** [comment]
門外漢なのでその辺存じません
cc: @kory33

**Comment by Lucky3028** [comment]
https://github.com/GiganticMinecraft/SeichiAssist/issues/342
こんなものがあって笑ってしまった...わらえない...

**Comment by Lucky3028** [comment]
どっちもやりますか？？？敵がわかないというのも魅力的だとは思いますので...

**Comment by stouma915** [comment]
![image](https://user-images.githubusercontent.com/62248740/101642414-56199080-3a76-11eb-8a97-20caa11c3123.png)
敵がわかないってやつはもう実装されている...?

**Comment by Lucky3028** [comment]
初めて知ったww

**Comment by Lucky3028** [comment]
アルカディアで聞いてみたところ、そんなに感触が良くないので保留で
