### ISSUE TITLE
マインスタックに採掘した分の物質が格納されない

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#80]
VCでの報告による。

**Comment by KisaragiEffective** [comment]
特別な条件が揃ったときに発覚するバグの可能性がある。
(s2整地3でエクスプロージョンを使用して石をほったところ、特に問題は生じていなかったため)

**Comment by kory33** [comment]
該当コードがかなり書き換わったのでsolvedとします
