### ISSUE TITLE
「スキルでのチェスト破壊は整地ワールドでのみ有効です」をアクションバーに表示する

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#83]
WorldGuardのメッセージみたいな感じに

**Comment by karayuumac** [comment]
参考：https://red.minecraftserver.jp/issues/8156

**Comment by KisaragiEffective** [comment]
![2022-03-20_20 40 58](https://user-images.githubusercontent.com/48310258/159160521-ac314564-c4b0-4798-bec1-10660bb5e412.png)
現在はもう表示される。クローズ。
