### ISSUE TITLE
経験値がオーバーフローしたプレイヤーがjoinするとサーバーがフリーズする(?)

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist#850]
要調査
https://discord.com/channels/237758724121427969/573131925158494220/790498383076524042

**Comment by unchama** [comment]
事象発生しているMCIDはNecomugi_331です。SeichiAssistDBのデータとworldフォルダに格納されたplayerdataファイルに何か手掛かりがあるかもしれない

**Comment by Lucky3028** [comment]
結果：#855

**Comment by KisaragiEffective** [comment]
多分 #856 で解消済み
