### ISSUE TITLE
make change as idea/#8808

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#851]

**Comment by Lucky3028** [comment]
スポーンで投擲物の発射キャンセルした場合にインベントリに存在するアイテムを消費しないようにする。
https://red.minecraftserver.jp/issues/8808

**Comment by Lucky3028** [comment]
- 弓矢
- 卵
- ポーション
- エンダーパール
- ファイアボール
- ラマの唾
- 雪玉
- 経験値瓶

**Comment by Lucky3028** [comment]
ラマの唾要ります？

**Comment by Lucky3028** [comment]
PlayerInteractEventだから関係ないですね、はい
