### ISSUE TITLE
サーバー初参加の際に配布されるアイテムの一部追加

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#914]
- [ ] ベイクドポテト1stを追加
- [ ] ツルハシに耐久3をつける
- [ ] 簡単なルール(整地の心得など)を書いた本を追加

第8回アイデア会議にて承認された
https://redmine.seichi.click/issues/9130
https://redmine.seichi.click/issues/9131
https://redmine.seichi.click/issues/9135

**Comment by KisaragiEffective** [comment]
ベイクドポテト**も**配布するということで良いのでしょうか？

----
permalink: https://github.com/GiganticMinecraft/SeichiAssist/blob/4cb5f6997a9cbe6cd872966950ec97c69efac5ab/src/main/scala/com/github/unchama/seichiassist/listener/PlayerJoinListener.scala#L92-L96

**Comment by Lucky3028** [comment]
はいそうですね
書き方が悪かったです、すみません

**Comment by Lucky3028** [comment]
本の内容に関しては後ほど書いときます

**Comment by Lucky3028** [comment]
本の内容
ーーー
基本的にはこの４つを守ってください。
ルール違反をした場合、BANなどの処罰が与えられます。

- 正規のアカウントを使用する
- 他人に迷惑をかけない
- 掘るときは上から綺麗に
- サーバーに負荷をかけない

整地の心得
整地ワールドでは以下のことを守って整地してください。

- 下から掘らず、上から掘るべし！
- 空中にブロックが残らないようにすべし！
- 水やマグマは除去すべし！
- 掘りぬいた後は綺麗に整えるべし！

上記、整地の心得に抵触するような掘り方をした場合は、72時間(3日)以内に状態の復旧をお願いします。
なお、第1整地ワールドのみ、整地の心得違反による処罰は実施致しません。

この他細かなルールや処罰の具体的な内容はHPをご確認ください。
ルールはサーバー内の情勢に応じて予告なく更新されることがあります。その際プレイヤーに個別通知することは致しませんので、ご利用の際にはお手数ですが随時最新のルールをご確認ください。
