### ISSUE TITLE
レベルアップ記念のガチャ券を棒メニューにある「運営からのガチャ券を受け取る」でまとめて受け取れるように

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#918]
題名通り

第8回アイデア会議にて承認された
https://redmine.seichi.click/issues/9160

**Comment by kory33** [comment]
これって元チケットにあるように「ようにもする(設定を追加して即時配布とガチャポイントへの統合を選べる)」ですか、それとも「ようにする(常にガチャポイントへ統合するようにする)」ですか？

**Comment by Lucky3028** [comment]
後者でー
