### ISSUE TITLE
フォームから公募した二つ名を実装する

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist#998]
https://docs.google.com/spreadsheets/d/1zYRlth0ux6-6D7uNZ1vMp31wCjH70cpjQhNj_nD522M/edit?usp=sharing

**Comment by Lucky3028** [comment]
チェック入れておきました

**Comment by soundofhorizon** [comment]
誰もやってなさそうなので、暇つぶし程度にやっておきます。
